<?php
// auto-generated by sfPropelCrud
// date: 2012/06/16 13:52:59
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmFileDownload/update') ?>

<?php echo object_input_hidden_tag($mlm_file_download, 'getFileId') ?>

<table>
<tbody>
<tr>
  <th>File type:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getFileType', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>File src:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getFileSrc', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>File name:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getFileName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Content type:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getContentType', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getStatusCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Remarks:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getRemarks', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_file_download, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_file_download, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_file_download, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_file_download->getFileId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmFileDownload/delete?file_id='.$mlm_file_download->getFileId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmFileDownload/show?file_id='.$mlm_file_download->getFileId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmFileDownload/list') ?>
<?php endif; ?>
</form>
