<?php
// auto-generated by sfPropelCrud
// date: 2012/06/16 13:52:59
?>
<h1>zMlmFileDownload</h1>

<table>
<thead>
<tr>
  <th>File</th>
  <th>File type</th>
  <th>File src</th>
  <th>File name</th>
  <th>Content type</th>
  <th>Status code</th>
  <th>Remarks</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_file_downloads as $mlm_file_download): ?>
<tr>
    <td><?php echo link_to($mlm_file_download->getFileId(), 'zMlmFileDownload/show?file_id='.$mlm_file_download->getFileId()) ?></td>
      <td><?php echo $mlm_file_download->getFileType() ?></td>
      <td><?php echo $mlm_file_download->getFileSrc() ?></td>
      <td><?php echo $mlm_file_download->getFileName() ?></td>
      <td><?php echo $mlm_file_download->getContentType() ?></td>
      <td><?php echo $mlm_file_download->getStatusCode() ?></td>
      <td><?php echo $mlm_file_download->getRemarks() ?></td>
      <td><?php echo $mlm_file_download->getCreatedBy() ?></td>
      <td><?php echo $mlm_file_download->getCreatedOn() ?></td>
      <td><?php echo $mlm_file_download->getUpdatedBy() ?></td>
      <td><?php echo $mlm_file_download->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmFileDownload/create') ?>
