<?php
// auto-generated by sfPropelCrud
// date: 2012/06/16 13:52:59
?>
<table>
<tbody>
<tr>
<th>File: </th>
<td><?php echo $mlm_file_download->getFileId() ?></td>
</tr>
<tr>
<th>File type: </th>
<td><?php echo $mlm_file_download->getFileType() ?></td>
</tr>
<tr>
<th>File src: </th>
<td><?php echo $mlm_file_download->getFileSrc() ?></td>
</tr>
<tr>
<th>File name: </th>
<td><?php echo $mlm_file_download->getFileName() ?></td>
</tr>
<tr>
<th>Content type: </th>
<td><?php echo $mlm_file_download->getContentType() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_file_download->getStatusCode() ?></td>
</tr>
<tr>
<th>Remarks: </th>
<td><?php echo $mlm_file_download->getRemarks() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_file_download->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_file_download->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_file_download->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_file_download->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmFileDownload/edit?file_id='.$mlm_file_download->getFileId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmFileDownload/list') ?>
