default:
  http_metas:
    content-type: text/html

  metas:
    title:        OFX Global Malaysia Administrator Backend
    robots:       OFX Global Malaysia Administrator Backend
    description:  OFX Global Malaysia Administrator Backend
    keywords:     OFX Global Malaysia Administrator Backend
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
