default:
  http_metas:
    content-type: text/html

  metas:
    title:        Maxim Trader Administrator Backend
    robots:       Maxim Trader Administrator Backend
    description:  Maxim Trader Administrator Backend
    keywords:     Maxim Trader Administrator Backend
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
