doTestDisabledMt4:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

correctRoi:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

all:
  is_secure:  on        # off is the default value anyway