<?php
// auto-generated by sfPropelCrud
// date: 2012/05/19 22:40:08
?>
<h1>zMlmEcreditPurchase</h1>

<table>
<thead>
<tr>
  <th>Ecredit</th>
  <th>Dist</th>
  <th>Balance</th>
  <th>Status code</th>
  <th>Remarks</th>
  <th>Approve reject datetime</th>
  <th>Approved by userid</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_ecredit_purchases as $mlm_ecredit_purchase): ?>
<tr>
    <td><?php echo link_to($mlm_ecredit_purchase->getEcreditId(), 'zMlmEcreditPurchase/show?ecredit_id='.$mlm_ecredit_purchase->getEcreditId()) ?></td>
      <td><?php echo $mlm_ecredit_purchase->getDistId() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getBalance() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getStatusCode() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getRemarks() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getApproveRejectDatetime() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getApprovedByUserid() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getCreatedBy() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getCreatedOn() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getUpdatedBy() ?></td>
      <td><?php echo $mlm_ecredit_purchase->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmEcreditPurchase/create') ?>
