<?php
// auto-generated by sfPropelCrud
// date: 2012/05/19 22:40:08
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmEcreditPurchase/update') ?>

<?php echo object_input_hidden_tag($mlm_ecredit_purchase, 'getEcreditId') ?>

<table>
<tbody>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($mlm_ecredit_purchase, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Balance*:</th>
  <td><?php echo object_input_tag($mlm_ecredit_purchase, 'getBalance', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($mlm_ecredit_purchase, 'getStatusCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Remarks:</th>
  <td><?php echo object_input_tag($mlm_ecredit_purchase, 'getRemarks', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Approve reject datetime:</th>
  <td><?php echo object_input_date_tag($mlm_ecredit_purchase, 'getApproveRejectDatetime', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Approved by userid:</th>
  <td><?php echo object_input_tag($mlm_ecredit_purchase, 'getApprovedByUserid', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_ecredit_purchase, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_ecredit_purchase, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_ecredit_purchase, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_ecredit_purchase, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_ecredit_purchase->getEcreditId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmEcreditPurchase/delete?ecredit_id='.$mlm_ecredit_purchase->getEcreditId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmEcreditPurchase/show?ecredit_id='.$mlm_ecredit_purchase->getEcreditId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmEcreditPurchase/list') ?>
<?php endif; ?>
</form>
