<?php
// auto-generated by sfPropelCrud
// date: 2012/05/19 22:40:08
?>
<table>
<tbody>
<tr>
<th>Ecredit: </th>
<td><?php echo $mlm_ecredit_purchase->getEcreditId() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $mlm_ecredit_purchase->getDistId() ?></td>
</tr>
<tr>
<th>Balance: </th>
<td><?php echo $mlm_ecredit_purchase->getBalance() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_ecredit_purchase->getStatusCode() ?></td>
</tr>
<tr>
<th>Remarks: </th>
<td><?php echo $mlm_ecredit_purchase->getRemarks() ?></td>
</tr>
<tr>
<th>Approve reject datetime: </th>
<td><?php echo $mlm_ecredit_purchase->getApproveRejectDatetime() ?></td>
</tr>
<tr>
<th>Approved by userid: </th>
<td><?php echo $mlm_ecredit_purchase->getApprovedByUserid() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_ecredit_purchase->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_ecredit_purchase->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_ecredit_purchase->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_ecredit_purchase->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmEcreditPurchase/edit?ecredit_id='.$mlm_ecredit_purchase->getEcreditId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmEcreditPurchase/list') ?>
