<?php
// auto-generated by sfPropelCrud
// date: 2012/05/17 13:44:09
?>
<h1>zMlmDistributor</h1>

<table>
<thead>
<tr>
  <th>Distributor</th>
  <th>Distributor code</th>
  <th>User</th>
  <th>Status code</th>
  <th>Full name</th>
  <th>Nickname</th>
  <th>Ic</th>
  <th>Country</th>
  <th>Address</th>
  <th>Address2</th>
  <th>City</th>
  <th>State</th>
  <th>Postcode</th>
  <th>Email</th>
  <th>Alternate email</th>
  <th>Contact</th>
  <th>Gender</th>
  <th>Dob</th>
  <th>Bank name</th>
  <th>Bank acc no</th>
  <th>Bank holder name</th>
  <th>Tree level</th>
  <th>Tree structure</th>
  <th>Master ib</th>
  <th>Master ib code</th>
  <th>Upline dist</th>
  <th>Upline dist code</th>
  <th>Rank</th>
  <th>Rank code</th>
  <th>Active datetime</th>
  <th>Leverage</th>
  <th>Spread</th>
  <th>Deposit currency</th>
  <th>Deposit amount</th>
  <th>Sign name</th>
  <th>Sign date</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_distributors as $mlm_distributor): ?>
<tr>
    <td><?php echo link_to($mlm_distributor->getDistributorId(), 'zMlmDistributor/show?distributor_id='.$mlm_distributor->getDistributorId()) ?></td>
      <td><?php echo $mlm_distributor->getDistributorCode() ?></td>
      <td><?php echo $mlm_distributor->getUserId() ?></td>
      <td><?php echo $mlm_distributor->getStatusCode() ?></td>
      <td><?php echo $mlm_distributor->getFullName() ?></td>
      <td><?php echo $mlm_distributor->getNickname() ?></td>
      <td><?php echo $mlm_distributor->getIc() ?></td>
      <td><?php echo $mlm_distributor->getCountry() ?></td>
      <td><?php echo $mlm_distributor->getAddress() ?></td>
      <td><?php echo $mlm_distributor->getAddress2() ?></td>
      <td><?php echo $mlm_distributor->getCity() ?></td>
      <td><?php echo $mlm_distributor->getState() ?></td>
      <td><?php echo $mlm_distributor->getPostcode() ?></td>
      <td><?php echo $mlm_distributor->getEmail() ?></td>
      <td><?php echo $mlm_distributor->getAlternateEmail() ?></td>
      <td><?php echo $mlm_distributor->getContact() ?></td>
      <td><?php echo $mlm_distributor->getGender() ?></td>
      <td><?php echo $mlm_distributor->getDob() ?></td>
      <td><?php echo $mlm_distributor->getBankName() ?></td>
      <td><?php echo $mlm_distributor->getBankAccNo() ?></td>
      <td><?php echo $mlm_distributor->getBankHolderName() ?></td>
      <td><?php echo $mlm_distributor->getTreeLevel() ?></td>
      <td><?php echo $mlm_distributor->getTreeStructure() ?></td>
      <td><?php echo $mlm_distributor->getMasterIbId() ?></td>
      <td><?php echo $mlm_distributor->getMasterIbCode() ?></td>
      <td><?php echo $mlm_distributor->getUplineDistId() ?></td>
      <td><?php echo $mlm_distributor->getUplineDistCode() ?></td>
      <td><?php echo $mlm_distributor->getRankId() ?></td>
      <td><?php echo $mlm_distributor->getRankCode() ?></td>
      <td><?php echo $mlm_distributor->getActiveDatetime() ?></td>
      <td><?php echo $mlm_distributor->getLeverage() ?></td>
      <td><?php echo $mlm_distributor->getSpread() ?></td>
      <td><?php echo $mlm_distributor->getDepositCurrency() ?></td>
      <td><?php echo $mlm_distributor->getDepositAmount() ?></td>
      <td><?php echo $mlm_distributor->getSignName() ?></td>
      <td><?php echo $mlm_distributor->getSignDate() ?></td>
      <td><?php echo $mlm_distributor->getCreatedBy() ?></td>
      <td><?php echo $mlm_distributor->getCreatedOn() ?></td>
      <td><?php echo $mlm_distributor->getUpdatedBy() ?></td>
      <td><?php echo $mlm_distributor->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmDistributor/create') ?>
