<?php
// auto-generated by sfPropelCrud
// date: 2012/05/17 13:44:09
?>
<table>
<tbody>
<tr>
<th>Distributor: </th>
<td><?php echo $mlm_distributor->getDistributorId() ?></td>
</tr>
<tr>
<th>Distributor code: </th>
<td><?php echo $mlm_distributor->getDistributorCode() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $mlm_distributor->getUserId() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_distributor->getStatusCode() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $mlm_distributor->getFullName() ?></td>
</tr>
<tr>
<th>Nickname: </th>
<td><?php echo $mlm_distributor->getNickname() ?></td>
</tr>
<tr>
<th>Ic: </th>
<td><?php echo $mlm_distributor->getIc() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $mlm_distributor->getCountry() ?></td>
</tr>
<tr>
<th>Address: </th>
<td><?php echo $mlm_distributor->getAddress() ?></td>
</tr>
<tr>
<th>Address2: </th>
<td><?php echo $mlm_distributor->getAddress2() ?></td>
</tr>
<tr>
<th>City: </th>
<td><?php echo $mlm_distributor->getCity() ?></td>
</tr>
<tr>
<th>State: </th>
<td><?php echo $mlm_distributor->getState() ?></td>
</tr>
<tr>
<th>Postcode: </th>
<td><?php echo $mlm_distributor->getPostcode() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $mlm_distributor->getEmail() ?></td>
</tr>
<tr>
<th>Alternate email: </th>
<td><?php echo $mlm_distributor->getAlternateEmail() ?></td>
</tr>
<tr>
<th>Contact: </th>
<td><?php echo $mlm_distributor->getContact() ?></td>
</tr>
<tr>
<th>Gender: </th>
<td><?php echo $mlm_distributor->getGender() ?></td>
</tr>
<tr>
<th>Dob: </th>
<td><?php echo $mlm_distributor->getDob() ?></td>
</tr>
<tr>
<th>Bank name: </th>
<td><?php echo $mlm_distributor->getBankName() ?></td>
</tr>
<tr>
<th>Bank acc no: </th>
<td><?php echo $mlm_distributor->getBankAccNo() ?></td>
</tr>
<tr>
<th>Bank holder name: </th>
<td><?php echo $mlm_distributor->getBankHolderName() ?></td>
</tr>
<tr>
<th>Tree level: </th>
<td><?php echo $mlm_distributor->getTreeLevel() ?></td>
</tr>
<tr>
<th>Tree structure: </th>
<td><?php echo $mlm_distributor->getTreeStructure() ?></td>
</tr>
<tr>
<th>Master ib: </th>
<td><?php echo $mlm_distributor->getMasterIbId() ?></td>
</tr>
<tr>
<th>Master ib code: </th>
<td><?php echo $mlm_distributor->getMasterIbCode() ?></td>
</tr>
<tr>
<th>Upline dist: </th>
<td><?php echo $mlm_distributor->getUplineDistId() ?></td>
</tr>
<tr>
<th>Upline dist code: </th>
<td><?php echo $mlm_distributor->getUplineDistCode() ?></td>
</tr>
<tr>
<th>Rank: </th>
<td><?php echo $mlm_distributor->getRankId() ?></td>
</tr>
<tr>
<th>Rank code: </th>
<td><?php echo $mlm_distributor->getRankCode() ?></td>
</tr>
<tr>
<th>Active datetime: </th>
<td><?php echo $mlm_distributor->getActiveDatetime() ?></td>
</tr>
<tr>
<th>Leverage: </th>
<td><?php echo $mlm_distributor->getLeverage() ?></td>
</tr>
<tr>
<th>Spread: </th>
<td><?php echo $mlm_distributor->getSpread() ?></td>
</tr>
<tr>
<th>Deposit currency: </th>
<td><?php echo $mlm_distributor->getDepositCurrency() ?></td>
</tr>
<tr>
<th>Deposit amount: </th>
<td><?php echo $mlm_distributor->getDepositAmount() ?></td>
</tr>
<tr>
<th>Sign name: </th>
<td><?php echo $mlm_distributor->getSignName() ?></td>
</tr>
<tr>
<th>Sign date: </th>
<td><?php echo $mlm_distributor->getSignDate() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_distributor->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_distributor->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_distributor->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_distributor->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmDistributor/edit?distributor_id='.$mlm_distributor->getDistributorId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmDistributor/list') ?>
