<?php
// auto-generated by sfPropelCrud
// date: 2012/11/12 16:07:08
?>
<table>
<tbody>
<tr>
<th>Request: </th>
<td><?php echo $mlm_mt4_demo_request->getRequestId() ?></td>
</tr>
<tr>
<th>First name: </th>
<td><?php echo $mlm_mt4_demo_request->getFirstName() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $mlm_mt4_demo_request->getEmail() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_mt4_demo_request->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_mt4_demo_request->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_mt4_demo_request->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_mt4_demo_request->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_mt4_demo_request->getUpdatedOn() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $mlm_mt4_demo_request->getCountry() ?></td>
</tr>
<tr>
<th>Phone number: </th>
<td><?php echo $mlm_mt4_demo_request->getPhoneNumber() ?></td>
</tr>
<tr>
<th>Last name: </th>
<td><?php echo $mlm_mt4_demo_request->getLastName() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $mlm_mt4_demo_request->getTitle() ?></td>
</tr>
<tr>
<th>Live demo: </th>
<td><?php echo $mlm_mt4_demo_request->getLiveDemo() ?></td>
</tr>
<tr>
<th>Address1: </th>
<td><?php echo $mlm_mt4_demo_request->getAddress1() ?></td>
</tr>
<tr>
<th>Address2: </th>
<td><?php echo $mlm_mt4_demo_request->getAddress2() ?></td>
</tr>
<tr>
<th>Agree of business: </th>
<td><?php echo $mlm_mt4_demo_request->getAgreeOfBusiness() ?></td>
</tr>
<tr>
<th>Risk disclosure: </th>
<td><?php echo $mlm_mt4_demo_request->getRiskDisclosure() ?></td>
</tr>
<tr>
<th>Country of citizen: </th>
<td><?php echo $mlm_mt4_demo_request->getCountryOfCitizen() ?></td>
</tr>
<tr>
<th>Dob day: </th>
<td><?php echo $mlm_mt4_demo_request->getDobDay() ?></td>
</tr>
<tr>
<th>Dob month: </th>
<td><?php echo $mlm_mt4_demo_request->getDobMonth() ?></td>
</tr>
<tr>
<th>Dob year: </th>
<td><?php echo $mlm_mt4_demo_request->getDobYear() ?></td>
</tr>
<tr>
<th>Ref: </th>
<td><?php echo $mlm_mt4_demo_request->getRefId() ?></td>
</tr>
<tr>
<th>Passport: </th>
<td><?php echo $mlm_mt4_demo_request->getPassport() ?></td>
</tr>
<tr>
<th>Subject: </th>
<td><?php echo $mlm_mt4_demo_request->getSubject() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmMt4DemoRequest/edit?request_id='.$mlm_mt4_demo_request->getRequestId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmMt4DemoRequest/list') ?>
