<?php


abstract class AP {
    const MOD_ADMIN = 'MOD_ADMIN';
    const MOD_MARKETING = 'MOD_MARKETING';
    const MOD_FINANCE = 'MOD_FINANCE';
    const MOD_REPORT = 'MOD_REPORT';
    const MOD_READONLY = 'MOD_READONLY';
    const MOD_TOTE_BONUS = 'MOD_TOTE_BONUS';

    const AL_READONLY = 'AL_READONLY';

    const AL_USER_LIST = 'AL_USER_LIST';
    const AL_USER_ROLE = 'AL_USER_ROLE';
    const AL_CHANGE_PASSWORD = 'AL_CHANGE_PASSWORD';
    const AL_SETTING = 'AL_SETTING';
    const AL_PACKAGE = 'AL_PACKAGE';
    const AL_BONUS = 'AL_BONUS';

    const AL_DIST_ADD = 'AL_DIST_ADD';
    const AL_DIST_LIST = 'AL_DIST_LIST';
    const AL_IB_LIST = 'AL_IB_LIST';
    const AL_SPONSOR_TREE = 'AL_SPONSOR_TREE';
    const AL_PLACEMENT_TREE = 'AL_PLACEMENT_TREE';
    const AL_PIPS_CALCULATOR = 'AL_PIPS_CALCULATOR';
    const AL_DAILY_PIPS_CALCULATOR = 'AL_DAILY_PIPS_CALCULATOR';
    const AL_FILE_UPLOAD = 'AL_FILE_UPLOAD';
    const AL_FUND_MANAGEMENT_UPLOAD = 'AL_FUND_MANAGEMENT_UPLOAD';
    const AL_SUPER_IB_LIST = 'AL_SUPER_IB_LIST';

    const AL_CUSTOMER_ENQUIRY = 'AL_CUSTOMER_ENQUIRY';
    const AL_DEMO_ACCOUNT_REQUEST = 'AL_DEMO_ACCOUNT_REQUEST';
    const AL_LIVE_ACCOUNT_REQUEST = 'AL_LIVE_ACCOUNT_REQUEST';
    const AL_DEBIT_CARD_APPLICATION = 'AL_DEBIT_CARD_APPLICATION';
    const AL_EZYCASH_CARD_APPLICATION = 'AL_EZYCASH_CARD_APPLICATION';

    const AL_RELOAD_MT4_FUND = 'AL_RELOAD_MT4_FUND';
    const AL_REFERRAL_BONUS = 'AL_REFERRAL_BONUS';
    const AL_PIPS_BONUS = 'AL_PIPS_BONUS';
    const AL_MT4_WITHDRAWAL = 'AL_MT4_WITHDRAWAL';

    const AL_ADVANCE_EPOINT = 'AL_ADVANCE_EPOINT';
    const AL_ADVANCE_ECASH = 'AL_ADVANCE_ECASH';
    const AL_DAILY_BONUS = 'AL_DAILY_BONUS';
    const AL_DAILY_SALES = 'AL_DAILY_SALES';
    const AL_CP3_WITHDRAWAL = 'AL_CP3_WITHDRAWAL';
    const AL_ECASH_WITHDRAWAL = 'AL_ECASH_WITHDRAWAL';
    const AL_ECASH_TRANSACTION = 'AL_ECASH_TRANSACTION';
    const AL_EPOINT_PURCHASE = 'AL_EPOINT_PURCHASE';
    const AL_EPOINT_TRANSFER = 'AL_EPOINT_TRANSFER';
    const AL_EPOINT_TRANSACTION = 'AL_EPOINT_TRANSACTION';
    const AL_MONTHLY_BONUS = 'AL_MONTHLY_BONUS';
    const AL_MONTHLY_SALES = 'AL_MONTHLY_SALES';
    const AL_PACKAGE_PURCHASE= 'AL_PACKAGE_PURCHASE';
    const AL_PACKAGE_UPGRADE = 'AL_PACKAGE_UPGRADE';
    const AL_CREDIT_ROLLING_POINT = 'AL_CREDIT_ROLLING_POINT';
    const AL_DEBIT_ROLLING_POINT = 'AL_DEBIT_ROLLING_POINT';

    const AL_REPORT_ROLLING_POINT= 'AL_REPORT_ROLLING_POINT';
    const AL_REPORT_CONVERT_ECASH_TO_EPOINT = 'AL_REPORT_CONVERT_ECASH_TO_EPOINT';
    const AL_REPORT_EPOINT_TRANSFER = 'AL_REPORT_EPOINT_TRANSFER';
    const AL_REPORT_GROUP_SALES = 'AL_REPORT_GROUP_SALES';
    const AL_REPORT_INDIVIDUAL_TRADER_SALES = 'AL_REPORT_INDIVIDUAL_TRADER_SALES';
    const AL_REPORT_MT4_WITHDRAWAL = 'AL_REPORT_MT4_WITHDRAWAL';
    const AL_REPORT_REFERRAL_BONUS = 'AL_REPORT_REFERRAL_BONUS';
    const AL_REPORT_TOTAL_MT4_RELOAD = 'AL_REPORT_TOTAL_MT4_RELOAD';
    const AL_REPORT_PACKAGE_PURCHASE = 'AL_REPORT_PACKAGE_PURCHASE';
    const AL_REPORT_PACKAGE_UPGRADE = 'AL_REPORT_PACKAGE_UPGRADE';
    const AL_REPORT_TOTAL_VOLUME_TRADED = 'AL_REPORT_TOTAL_VOLUME_TRADED';

    const AL_TOTE_BONUS = 'AL_TOTE_BONUS';
}