buyingHistoryListing:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

buyShare:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

openTransactionListing:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

reinvestEshare:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

sellingHistoryListing:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

sellShare:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

tradingCenter:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

all:
  is_secure:  off        # off is the default value anyway