# default rules
homepage:
  url:   /
  param: { module: home, action: login }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

epoint_log:
  url:   /member/cp1Log
  param: { module: member, action: epointLog }

ecash_log:
  url:   /member/cp2Log
  param: { module: member, action: ecashLog }

ecash_withdrawal:
  url:   /member/cp2Withdrawal
  param: { module: member, action: ecashWithdrawal }

maintenance_log:
  url:   /member/cp3Log
  param: { module: member, action: maintenanceLog }

convert_ecash_to_epoint:
  url:   /member/convertCp2ToCp1
  param: { module: member, action: convertEcashToEpoint }

transfer_epoint:
  url:   /member/transferCp1
  param: { module: member, action: transferEpoint }

epoint_purchase:
  url:   /member/cp1Purchase
  param: { module: member, action: epointPurchase }

affiliateLink:
  url:   /a/:id
  param: { module: member, action: register }

default:
  url:   /:module/:action/*