default:
  http_metas:
    content-type: text/html

  metas:
    title:        OFX Global Malaysia
    robots:       OFX Global Malaysia
    description:  OFX Global Malaysia
    keywords:     OFX Global Malaysia
    language:     cn

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
