<?php
// auto-generated by sfPropelCrud
// date: 2012/11/21 21:07:46
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmMemberApplication/update') ?>

<?php echo object_input_hidden_tag($mlm_member_application, 'getMemberId') ?>

<table>
<tbody>
<tr>
  <th>Full name:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getFullName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Contact:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getContact', array (
  'size' => 30,
)) ?></td>
</tr>
<tr>
  <th>Qq:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getQq', array (
  'size' => 30,
)) ?></td>
</tr>
<tr>
  <th>Gender:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getGender', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Country:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getCountry', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dob:</th>
  <td><?php echo object_input_date_tag($mlm_member_application, 'getDob', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getStatusCode', array (
  'size' => 30,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_member_application, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_member_application, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_member_application, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_member_application->getMemberId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmMemberApplication/delete?member_id='.$mlm_member_application->getMemberId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmMemberApplication/show?member_id='.$mlm_member_application->getMemberId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmMemberApplication/list') ?>
<?php endif; ?>
</form>
