<?php
// auto-generated by sfPropelCrud
// date: 2012/11/21 21:07:46
?>
<table>
<tbody>
<tr>
<th>Member: </th>
<td><?php echo $mlm_member_application->getMemberId() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $mlm_member_application->getFullName() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $mlm_member_application->getEmail() ?></td>
</tr>
<tr>
<th>Contact: </th>
<td><?php echo $mlm_member_application->getContact() ?></td>
</tr>
<tr>
<th>Qq: </th>
<td><?php echo $mlm_member_application->getQq() ?></td>
</tr>
<tr>
<th>Gender: </th>
<td><?php echo $mlm_member_application->getGender() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $mlm_member_application->getCountry() ?></td>
</tr>
<tr>
<th>Dob: </th>
<td><?php echo $mlm_member_application->getDob() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_member_application->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_member_application->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_member_application->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_member_application->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_member_application->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmMemberApplication/edit?member_id='.$mlm_member_application->getMemberId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmMemberApplication/list') ?>
