<?php
// auto-generated by sfPropelCrud
// date: 2012/11/21 21:11:05
?>
<table>
<tbody>
<tr>
<th>Questionnaire: </th>
<td><?php echo $mlm_member_questionnaire->getQuestionnaireId() ?></td>
</tr>
<tr>
<th>Member: </th>
<td><?php echo $mlm_member_questionnaire->getMemberId() ?></td>
</tr>
<tr>
<th>Q1: </th>
<td><?php echo $mlm_member_questionnaire->getQ1() ?></td>
</tr>
<tr>
<th>Q2: </th>
<td><?php echo $mlm_member_questionnaire->getQ2() ?></td>
</tr>
<tr>
<th>Q3: </th>
<td><?php echo $mlm_member_questionnaire->getQ3() ?></td>
</tr>
<tr>
<th>Q4: </th>
<td><?php echo $mlm_member_questionnaire->getQ4() ?></td>
</tr>
<tr>
<th>Q5: </th>
<td><?php echo $mlm_member_questionnaire->getQ5() ?></td>
</tr>
<tr>
<th>Q6: </th>
<td><?php echo $mlm_member_questionnaire->getQ6() ?></td>
</tr>
<tr>
<th>Q7: </th>
<td><?php echo $mlm_member_questionnaire->getQ7() ?></td>
</tr>
<tr>
<th>Q8: </th>
<td><?php echo $mlm_member_questionnaire->getQ8() ?></td>
</tr>
<tr>
<th>S1: </th>
<td><?php echo $mlm_member_questionnaire->getS1() ?></td>
</tr>
<tr>
<th>S2: </th>
<td><?php echo $mlm_member_questionnaire->getS2() ?></td>
</tr>
<tr>
<th>S3: </th>
<td><?php echo $mlm_member_questionnaire->getS3() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_member_questionnaire->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_member_questionnaire->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_member_questionnaire->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_member_questionnaire->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_member_questionnaire->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmMemberQuestionnaire/edit?questionnaire_id='.$mlm_member_questionnaire->getQuestionnaireId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmMemberQuestionnaire/list') ?>
