<?php
// auto-generated by sfPropelCrud
// date: 2012/09/07 00:19:28
?>
<h1>zMlmDistMt4</h1>

<table>
<thead>
<tr>
  <th>Mt4</th>
  <th>Dist</th>
  <th>Mt4 user name</th>
  <th>Mt4 password</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_dist_mt4s as $mlm_dist_mt4): ?>
<tr>
    <td><?php echo link_to($mlm_dist_mt4->getMt4Id(), 'zMlmDistMt4/show?mt4_id='.$mlm_dist_mt4->getMt4Id()) ?></td>
      <td><?php echo $mlm_dist_mt4->getDistId() ?></td>
      <td><?php echo $mlm_dist_mt4->getMt4UserName() ?></td>
      <td><?php echo $mlm_dist_mt4->getMt4Password() ?></td>
      <td><?php echo $mlm_dist_mt4->getCreatedBy() ?></td>
      <td><?php echo $mlm_dist_mt4->getCreatedOn() ?></td>
      <td><?php echo $mlm_dist_mt4->getUpdatedBy() ?></td>
      <td><?php echo $mlm_dist_mt4->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmDistMt4/create') ?>
