<?php
// auto-generated by sfPropelCrud
// date: 2012/11/12 16:07:08
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmMt4DemoRequest/update') ?>

<?php echo object_input_hidden_tag($mlm_mt4_demo_request, 'getRequestId') ?>

<table>
<tbody>
<tr>
  <th>First name:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getFirstName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Status code*:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getStatusCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_mt4_demo_request, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_mt4_demo_request, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Country:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getCountry', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Phone number:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getPhoneNumber', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Last name:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getLastName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Live demo:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getLiveDemo', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Address1:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getAddress1', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Address2:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getAddress2', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Agree of business:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getAgreeOfBusiness', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Risk disclosure:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getRiskDisclosure', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Country of citizen:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getCountryOfCitizen', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dob day:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getDobDay', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dob month:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getDobMonth', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dob year:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getDobYear', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Ref:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getRefId', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Passport:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getPassport', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Subject:</th>
  <td><?php echo object_input_tag($mlm_mt4_demo_request, 'getSubject', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_mt4_demo_request->getRequestId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmMt4DemoRequest/delete?request_id='.$mlm_mt4_demo_request->getRequestId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmMt4DemoRequest/show?request_id='.$mlm_mt4_demo_request->getRequestId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmMt4DemoRequest/list') ?>
<?php endif; ?>
</form>
