<?php
// auto-generated by sfPropelCrud
// date: 2012/05/17 13:43:36
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmMd4Account/update') ?>

<?php echo object_input_hidden_tag($mlm_md4_account, 'getMd4Id') ?>

<table>
<tbody>
<tr>
  <th>Distributor:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getDistributorId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Package*:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getPackageId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Md user name:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getMdUserName', array (
  'size' => 25,
)) ?></td>
</tr>
<tr>
  <th>Investor password:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getInvestorPassword', array (
  'size' => 25,
)) ?></td>
</tr>
<tr>
  <th>Normal password:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getNormalPassword', array (
  'size' => 25,
)) ?></td>
</tr>
<tr>
  <th>Serial no:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getSerialNo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getStatusCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_md4_account, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_md4_account, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_md4_account, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_md4_account->getMd4Id()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmMd4Account/delete?md4_id='.$mlm_md4_account->getMd4Id(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmMd4Account/show?md4_id='.$mlm_md4_account->getMd4Id()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmMd4Account/list') ?>
<?php endif; ?>
</form>
