<?php
// auto-generated by sfPropelCrud
// date: 2013/08/10 00:16:00
?>
<table>
<tbody>
<tr>
<th>Abfx: </th>
<td><?php echo $abfx_dist_mt4->getAbfxId() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $abfx_dist_mt4->getDistId() ?></td>
</tr>
<tr>
<th>Dist code: </th>
<td><?php echo $abfx_dist_mt4->getDistCode() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $abfx_dist_mt4->getEmail() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $abfx_dist_mt4->getFullName() ?></td>
</tr>
<tr>
<th>Mt4 user name: </th>
<td><?php echo $abfx_dist_mt4->getMt4UserName() ?></td>
</tr>
<tr>
<th>Mt4 password: </th>
<td><?php echo $abfx_dist_mt4->getMt4Password() ?></td>
</tr>
<tr>
<th>File name: </th>
<td><?php echo $abfx_dist_mt4->getFileName() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $abfx_dist_mt4->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $abfx_dist_mt4->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $abfx_dist_mt4->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $abfx_dist_mt4->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $abfx_dist_mt4->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'abfxDistMt4/edit?abfx_id='.$abfx_dist_mt4->getAbfxId()) ?>
&nbsp;<?php echo link_to('list', 'abfxDistMt4/list') ?>
