<?php
// auto-generated by sfPropelCrud
// date: 2012/06/17 16:05:48
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmPipCsv/update') ?>

<?php echo object_input_hidden_tag($mlm_pip_csv, 'getPipId') ?>

<table>
<tbody>
<tr>
  <th>File:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getFileId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Pips string:</th>
  <td><?php echo object_textarea_tag($mlm_pip_csv, 'getPipsString', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Login:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getLoginId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Login name*:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getLoginName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Deposit:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getDeposit', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Withdraw:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getWithdraw', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>In out:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getInOut', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Credit:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getCredit', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Volume:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getVolume', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Commission:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getCommission', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Taxes:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getTaxes', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Agent:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getAgent', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Storage:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getStorage', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Profit:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getProfit', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Last balance:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getLastBalance', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Status code*:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getStatusCode', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_pip_csv, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_pip_csv, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_pip_csv, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_pip_csv->getPipId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmPipCsv/delete?pip_id='.$mlm_pip_csv->getPipId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmPipCsv/show?pip_id='.$mlm_pip_csv->getPipId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmPipCsv/list') ?>
<?php endif; ?>
</form>
