<?php
// auto-generated by sfPropelCrud
// date: 2012/06/17 16:05:48
?>
<h1>zMlmPipCsv</h1>

<table>
<thead>
<tr>
  <th>Pip</th>
  <th>File</th>
  <th>Pips string</th>
  <th>Login</th>
  <th>Login name</th>
  <th>Deposit</th>
  <th>Withdraw</th>
  <th>In out</th>
  <th>Credit</th>
  <th>Volume</th>
  <th>Commission</th>
  <th>Taxes</th>
  <th>Agent</th>
  <th>Storage</th>
  <th>Profit</th>
  <th>Last balance</th>
  <th>Status code</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_pip_csvs as $mlm_pip_csv): ?>
<tr>
    <td><?php echo link_to($mlm_pip_csv->getPipId(), 'zMlmPipCsv/show?pip_id='.$mlm_pip_csv->getPipId()) ?></td>
      <td><?php echo $mlm_pip_csv->getFileId() ?></td>
      <td><?php echo $mlm_pip_csv->getPipsString() ?></td>
      <td><?php echo $mlm_pip_csv->getLoginId() ?></td>
      <td><?php echo $mlm_pip_csv->getLoginName() ?></td>
      <td><?php echo $mlm_pip_csv->getDeposit() ?></td>
      <td><?php echo $mlm_pip_csv->getWithdraw() ?></td>
      <td><?php echo $mlm_pip_csv->getInOut() ?></td>
      <td><?php echo $mlm_pip_csv->getCredit() ?></td>
      <td><?php echo $mlm_pip_csv->getVolume() ?></td>
      <td><?php echo $mlm_pip_csv->getCommission() ?></td>
      <td><?php echo $mlm_pip_csv->getTaxes() ?></td>
      <td><?php echo $mlm_pip_csv->getAgent() ?></td>
      <td><?php echo $mlm_pip_csv->getStorage() ?></td>
      <td><?php echo $mlm_pip_csv->getProfit() ?></td>
      <td><?php echo $mlm_pip_csv->getLastBalance() ?></td>
      <td><?php echo $mlm_pip_csv->getStatusCode() ?></td>
      <td><?php echo $mlm_pip_csv->getCreatedBy() ?></td>
      <td><?php echo $mlm_pip_csv->getCreatedOn() ?></td>
      <td><?php echo $mlm_pip_csv->getUpdatedBy() ?></td>
      <td><?php echo $mlm_pip_csv->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmPipCsv/create') ?>
