<?php
// auto-generated by sfPropelCrud
// date: 2012/06/17 16:05:48
?>
<table>
<tbody>
<tr>
<th>Pip: </th>
<td><?php echo $mlm_pip_csv->getPipId() ?></td>
</tr>
<tr>
<th>File: </th>
<td><?php echo $mlm_pip_csv->getFileId() ?></td>
</tr>
<tr>
<th>Pips string: </th>
<td><?php echo $mlm_pip_csv->getPipsString() ?></td>
</tr>
<tr>
<th>Login: </th>
<td><?php echo $mlm_pip_csv->getLoginId() ?></td>
</tr>
<tr>
<th>Login name: </th>
<td><?php echo $mlm_pip_csv->getLoginName() ?></td>
</tr>
<tr>
<th>Deposit: </th>
<td><?php echo $mlm_pip_csv->getDeposit() ?></td>
</tr>
<tr>
<th>Withdraw: </th>
<td><?php echo $mlm_pip_csv->getWithdraw() ?></td>
</tr>
<tr>
<th>In out: </th>
<td><?php echo $mlm_pip_csv->getInOut() ?></td>
</tr>
<tr>
<th>Credit: </th>
<td><?php echo $mlm_pip_csv->getCredit() ?></td>
</tr>
<tr>
<th>Volume: </th>
<td><?php echo $mlm_pip_csv->getVolume() ?></td>
</tr>
<tr>
<th>Commission: </th>
<td><?php echo $mlm_pip_csv->getCommission() ?></td>
</tr>
<tr>
<th>Taxes: </th>
<td><?php echo $mlm_pip_csv->getTaxes() ?></td>
</tr>
<tr>
<th>Agent: </th>
<td><?php echo $mlm_pip_csv->getAgent() ?></td>
</tr>
<tr>
<th>Storage: </th>
<td><?php echo $mlm_pip_csv->getStorage() ?></td>
</tr>
<tr>
<th>Profit: </th>
<td><?php echo $mlm_pip_csv->getProfit() ?></td>
</tr>
<tr>
<th>Last balance: </th>
<td><?php echo $mlm_pip_csv->getLastBalance() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_pip_csv->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_pip_csv->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_pip_csv->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_pip_csv->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_pip_csv->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmPipCsv/edit?pip_id='.$mlm_pip_csv->getPipId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmPipCsv/list') ?>
