<?php
// auto-generated by sfPropelCrud
// date: 2012/05/19 22:37:17
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmReloadTopupHistory/update') ?>

<?php echo object_input_hidden_tag($mlm_reload_topup_history, 'getReloadId') ?>

<table>
<tbody>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($mlm_reload_topup_history, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Transaction code:</th>
  <td><?php echo object_input_tag($mlm_reload_topup_history, 'getTransactionCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Balance*:</th>
  <td><?php echo object_input_tag($mlm_reload_topup_history, 'getBalance', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($mlm_reload_topup_history, 'getStatusCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Remarks:</th>
  <td><?php echo object_input_tag($mlm_reload_topup_history, 'getRemarks', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_reload_topup_history, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_reload_topup_history, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_reload_topup_history, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_reload_topup_history, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_reload_topup_history->getReloadId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmReloadTopupHistory/delete?reload_id='.$mlm_reload_topup_history->getReloadId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmReloadTopupHistory/show?reload_id='.$mlm_reload_topup_history->getReloadId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmReloadTopupHistory/list') ?>
<?php endif; ?>
</form>
