<?php
// auto-generated by sfPropelCrud
// date: 2012/05/19 22:37:17
?>
<table>
<tbody>
<tr>
<th>Reload: </th>
<td><?php echo $mlm_reload_topup_history->getReloadId() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $mlm_reload_topup_history->getDistId() ?></td>
</tr>
<tr>
<th>Transaction code: </th>
<td><?php echo $mlm_reload_topup_history->getTransactionCode() ?></td>
</tr>
<tr>
<th>Balance: </th>
<td><?php echo $mlm_reload_topup_history->getBalance() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_reload_topup_history->getStatusCode() ?></td>
</tr>
<tr>
<th>Remarks: </th>
<td><?php echo $mlm_reload_topup_history->getRemarks() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_reload_topup_history->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_reload_topup_history->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_reload_topup_history->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_reload_topup_history->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmReloadTopupHistory/edit?reload_id='.$mlm_reload_topup_history->getReloadId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmReloadTopupHistory/list') ?>
