<?php
// auto-generated by sfPropelCrud
// date: 2012/05/29 07:08:12
?>
<?php

/**
 * zMlmDistBankslip actions.
 *
 * @package    sf_sandbox
 * @subpackage zMlmDistBankslip
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class zMlmDistBankslipActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('zMlmDistBankslip', 'list');
  }

  public function executeList()
  {
    $this->mlm_dist_bankslips = MlmDistBankslipPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->mlm_dist_bankslip = MlmDistBankslipPeer::retrieveByPk($this->getRequestParameter('bankslip_id'));
    $this->forward404Unless($this->mlm_dist_bankslip);
  }

  public function executeCreate()
  {
    $this->mlm_dist_bankslip = new MlmDistBankslip();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->mlm_dist_bankslip = MlmDistBankslipPeer::retrieveByPk($this->getRequestParameter('bankslip_id'));
    $this->forward404Unless($this->mlm_dist_bankslip);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('bankslip_id'))
    {
      $mlm_dist_bankslip = new MlmDistBankslip();
    }
    else
    {
      $mlm_dist_bankslip = MlmDistBankslipPeer::retrieveByPk($this->getRequestParameter('bankslip_id'));
      $this->forward404Unless($mlm_dist_bankslip);
    }

    $mlm_dist_bankslip->setBankslipId($this->getRequestParameter('bankslip_id'));
    $mlm_dist_bankslip->setDistId($this->getRequestParameter('dist_id'));
    $mlm_dist_bankslip->setRankId($this->getRequestParameter('rank_id'));
    $mlm_dist_bankslip->setRankCode($this->getRequestParameter('rank_code'));
    $mlm_dist_bankslip->setAmount($this->getRequestParameter('amount'));
    $mlm_dist_bankslip->setTransactionType($this->getRequestParameter('transaction_type'));
    $mlm_dist_bankslip->setImageSrc($this->getRequestParameter('image_src'));
    $mlm_dist_bankslip->setStatusCode($this->getRequestParameter('status_code'));
    $mlm_dist_bankslip->setRemarks($this->getRequestParameter('remarks'));
    if ($this->getRequestParameter('approve_reject_datetime'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('approve_reject_datetime'), $this->getUser()->getCulture());
      $mlm_dist_bankslip->setApproveRejectDatetime("$y-$m-$d");
    }
    $mlm_dist_bankslip->setApprovedByUserid($this->getRequestParameter('approved_by_userid'));
    $mlm_dist_bankslip->setCreatedBy($this->getRequestParameter('created_by'));
    if ($this->getRequestParameter('created_on'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('created_on'), $this->getUser()->getCulture());
      $mlm_dist_bankslip->setCreatedOn("$y-$m-$d");
    }
    $mlm_dist_bankslip->setUpdatedBy($this->getRequestParameter('updated_by'));
    if ($this->getRequestParameter('updated_on'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('updated_on'), $this->getUser()->getCulture());
      $mlm_dist_bankslip->setUpdatedOn("$y-$m-$d");
    }

    $mlm_dist_bankslip->save();

    return $this->redirect('zMlmDistBankslip/show?bankslip_id='.$mlm_dist_bankslip->getBankslipId());
  }

  public function executeDelete()
  {
    $mlm_dist_bankslip = MlmDistBankslipPeer::retrieveByPk($this->getRequestParameter('bankslip_id'));

    $this->forward404Unless($mlm_dist_bankslip);

    $mlm_dist_bankslip->delete();

    return $this->redirect('zMlmDistBankslip/list');
  }
}
