<?php
// auto-generated by sfPropelCrud
// date: 2012/04/20 19:13:40
?>
<?php use_helper('Object') ?>
<?php use_helper('I18N') ?>
<!-- TinyMCE -->
<script type="text/javascript">
$(function() {
    $("#btnApprove").button({
        icons: {
            primary: "ui-icon-circle-check"
        }
    }).click(function(event){
        event.preventDefault();

        if ($.trim($('#mt4Id').val()) == "") {
            alert("MT4 ID is empty.");
            $('#mt4Id').focus();
        } else {
            var answer = confirm("Are you sure want to approve this member package upgrade?")
            if (answer){
                waiting();
                $("#status_code").val("COMPLETE");
                $("#upgradeForm").submit();
            }
        }
    });
    $("#btnReject").button({
        icons: {
            primary: "ui-icon-circle-close"
        }
    }).click(function(event){
        event.preventDefault();

        var answer = confirm("Are you sure want to reject this member package upgrade?")
        if (answer){
            waiting();
            $("#status_code").val("REJECT");
            $("#upgradeForm").submit();
        }
    });
    $("#btnCancel").button({
        icons: {
            primary: "ui-icon-circle-arrow-w"
        }
    }).click(function(){
        $("#upgradeForm").attr("action", "<?php echo url_for("/finance/packageUpgradeHistory")?>");
    });

});
</script>

<?php echo form_tag('finance/updatePackageUpgrade', 'id=upgradeForm') ?>

<?php echo object_input_hidden_tag($packageUpgradeHistory, 'getUpgradeId') ?>

<div style="padding: 10px; top: 10px; width: 95%">
    <div class="portlet">
        <div class="portlet-header">Package Upgrade History Details</div>
        <div class="portlet-content">
            <table class="sf_admin_list" cellpadding="3" width="100%">
                <tbody>
                <tr>
                    <td colspan="2">
                        <?php if ($sf_flash->has('successMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-highlight ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-info"></span>
                                    <strong><?php echo $sf_flash->get('successMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if ($sf_flash->has('errorMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-error ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                                    <strong><?php echo $sf_flash->get('errorMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php
                    $existDist = MlmDistributorPeer::retrieveByPK($packageUpgradeHistory->getDistId());
                ?>
                <tr>
                    <th class="caption">Distributor Code :</th>
                    <td class="value"><?php
                        echo $existDist->getDistributorCode() ?></td>
                </tr>
                <tr>
                    <th class="caption">Full Name :</th>
                    <td class="value"><?php
                        echo $existDist->getFullName() ?></td>
                </tr>
                <?php
                $mt4Username = "";
                $mt4Password = "";
                $mt4Id = "";
                if ($packageUpgradeHistory->getMt4UserName() != null) {
                    $c = new Criteria();
                    $c->add(MlmDistMt4Peer::DIST_ID, $packageUpgradeHistory->getDistId());
                    $c->add(MlmDistMt4Peer::MT4_USER_NAME, $packageUpgradeHistory->getMt4UserName());
                    $mlm_dist_mt4 = MlmDistMt4Peer::doSelectOne($c);

                    if ($mlm_dist_mt4) {
                        $mt4Username = $mlm_dist_mt4->getMt4UserName();
                        $mt4Password = $mlm_dist_mt4->getMt4Password();
                        $mt4Id = $mlm_dist_mt4->getMt4Id();
                    }
                }
                ?>
                <tr>
                    <th class="caption">MT4 ID :</th>
                    <td class="value">
                        <input type="text" name="mt4Id" id="mt4Id" value="<?php echo $mt4Username?>">
                        <input type="hidden" name="distMt4AccountId" id="distMt4AccountId" value="<?php echo $mt4Id?>">
                    </td>
                </tr>
                <tr>
                    <th class="caption">MT4 Password :</th>
                    <td class="value"><input type="text" name="mt4Password" id="mt4Password" value="<?php echo $mt4Password?>"></td>
                </tr>
                <tr>
                    <th class="caption">Amount *:</th>
                    <td class="value"><?php echo object_input_tag($packageUpgradeHistory, 'getAmount', array(
                                                                                           'size' => 7,
                                                                                            'readonly' => 'readonly',
                                                                                      )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Status code:</th>
                    <td class="value">
                        <input id="status_code" name="status_code" readonly="readonly" value="<?php echo $packageUpgradeHistory->getStatusCode();?>">
                    </td>
                </tr>
                <tr>
                    <th class="caption">Remarks:</th>
                    <td class="value"><?php echo object_textarea_tag($packageUpgradeHistory, 'getRemarks', array(
                                                                                                          'size' => '30x3',
                                                                                                     )) ?></td>
                </tr>
                </tbody>
            </table>
            <hr/>
            <?php if ($packageUpgradeHistory->getStatusCode() == Globals::STATUS_ACTIVE) { ?>
                <button id="btnApprove">Approve</button>
                <button id="btnReject">Reject</button>
            <?php } ?>
            <button id="btnCancel">Cancel</button>
<!--            &nbsp;--><?php //echo link_to('cancel', 'finance/ecashWithdrawal', array("id" => "btnCancel")) ?>
        </div>
    </div>
</div>
</form>