<?php
// auto-generated by sfPropelCrud
// date: 2012/04/20 19:13:40
echo "<link href='/sf/sf_admin/css/main.css' media='screen' type='text/css' rel='stylesheet'>";
?>
<?php use_helper('Object') ?>
<?php use_helper('I18N') ?>
<!-- TinyMCE -->
<script type="text/javascript">
$(function() {
    $("#btnSave").button({
        icons: {
            primary: "ui-icon-circle-check"
        }
    });
    $("#btnCancel").button({
        icons: {
            primary: "ui-icon-circle-arrow-w"
        }
    }).click(function(){
        $("#purchaseForm").attr("action", "<?php echo url_for("/finance/productPurchase")?>");
    });
});
</script>

<?php echo form_tag('finance/updateProductPurchase', 'id=purchaseForm') ?>

<?php echo object_input_hidden_tag($mlmProductPurchaseHistory, 'getHistoryId') ?>

<div style="padding: 10px; top: 10px; width: 95%">
    <div class="portlet">
        <div class="portlet-header">Product Purchase Details</div>
        <div class="portlet-content">
            <table class="sf_admin_list" cellpadding="3" width="100%">
                <tbody>
                <tr>
                    <td colspan="2">
                        <?php if ($sf_flash->has('successMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-highlight ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-info"></span>
                                    <strong><?php echo $sf_flash->get('successMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if ($sf_flash->has('errorMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-error ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                                    <strong><?php echo $sf_flash->get('errorMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php
                    $existDist = MlmDistributorPeer::retrieveByPK($mlmProductPurchaseHistory->getDistId());
                ?>
                <tr>
                    <th class="caption">Distributor Code :</th>
                    <td class="value"><?php
                        echo $existDist->getDistributorCode() ?></td>
                </tr>
                <tr>
                    <th class="caption">Full Name :</th>
                    <td class="value"><?php
                        echo $existDist->getFullName() ?></td>
                </tr>
                <tr>
                    <th class="caption">Total Amount *:</th>
                    <td class="value"><?php echo object_input_tag($mlmProductPurchaseHistory, 'getTotalAmount', array(
                                                                                           'size' => 7,
                                                                                            'readonly' => 'readonly',
                                                                                      )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Status Code:</th>
                    <td class="value"><?php echo object_input_tag($mlmProductPurchaseHistory, 'getStatusCode', array(
                                                                                            'readonly' => 'readonly',
                                                                                      )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Status code:</th>
                    <td class="value"><?php
                        $arr = array();
                        $arr['DELIVERED'] = 'DELIVERED';
                        $arr['REJECT'] = 'REJECT';
                        echo select_tag('status_code', options_for_select($arr, $mlmProductPurchaseHistory->getStatusCode()));
                     ?></td>
                </tr>
                <tr>
                    <th class="caption">Remarks:</th>
                    <td class="value"><?php echo object_textarea_tag($mlmProductPurchaseHistory, 'getRemarks', array(
                                                                                                          'size' => '30x3',
                                                                                                     )) ?></td>
                </tr>
                </tbody>
            </table>

            <br>
            <div id="sf_admin_container">
                <h3>Product Details</h3>
            <div class="portlet-content" id="sf_admin_content" style="width: 98%">
            <table class="sf_admin_list" width="100%">
                <thead>
                <tr>
                    <th></th>
                    <th>Package name</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th>Total Amount</th>
                </tr>
                </thead>
                <tbody>
                <?php
                $index = 1;
                foreach ($mlmProductPurchaseHistoryDetails as $mlmProductPurchaseHistoryDetail):
                    if ($className == "sf_admin_row_0") {
                        $className = "sf_admin_row_1";
                    } else {
                        $className = "sf_admin_row_0";
                    }
                    $product = MlmMaxStorePeer::retrieveByPK($mlmProductPurchaseHistoryDetail->getProductId());
                    ?>
                <tr class="<?php echo $className?>">
                    <td><?php echo $index++; ?></td>
                    <td><?php echo $product->getProductName() ?></td>
                    <td><?php echo $mlmProductPurchaseHistoryDetail->getPrice() ?></td>
                    <td><?php echo $mlmProductPurchaseHistoryDetail->getQty() ?></td>
                    <td><?php echo $mlmProductPurchaseHistoryDetail->getTotalAmount() ?></td>
                </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            </div>
            </div>
            <hr/>
            <?php if ($mlmProductPurchaseHistory->getStatusCode() == Globals::STATUS_COMPLETE || $mlmProductPurchaseHistory->getStatusCode() == Globals::STATUS_REJECT) {

            } else {
            ?>
            <button id="btnSave">Save</button>
            <?php } ?>
            <button id="btnCancel">Cancel</button>
<!--            &nbsp;--><?php //echo link_to('cancel', 'finance/ecashWithdrawal', array("id" => "btnCancel")) ?>
        </div>
    </div>
</div>
</form>