correctRwallet:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

dailyBonus:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doAutoConvertSSS:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doUpdateAsssPendingToAsssPairing:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doAutoConvertEShare:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doDisabledMt4AndCheckForMaturity:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doGeneratePairingPoint:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doGeneratePairingPointProcessing:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doRerunRshare:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doTestDisabledMt4:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

forceRunDisabledMt4AndCheckForMaturity:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

index:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doTesting:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

report:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

report2:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

reverseErrorToPairing:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

removeDuplicateErrorRecord:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

terminateContractAndRemoveShare:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

updatePairingCreatedDate:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

all:
  is_secure:  on        # off is the default value anyway