correctRwallet:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

dailyBonus:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doDisabledMt4AndCheckForMaturity:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doGeneratePairingPoint:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

doTestDisabledMt4:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

report:
  is_secure:   off
  credentials: [[ MAXIM_DISTRIBUTOR ]]

all:
  is_secure:  on        # off is the default value anyway