<?php
// auto-generated by sfPropelCrud
// date: 2013/12/31 10:47:22
?>
<?php use_helper('Object') ?>

<?php echo form_tag('appEmailDatabase/update') ?>

<?php echo object_input_hidden_tag($app_email_database, 'getEmailId') ?>

<table>
<tbody>
<tr>
  <th>Email*:</th>
  <td><?php echo object_input_tag($app_email_database, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Status code*:</th>
  <td><?php echo object_input_tag($app_email_database, 'getStatusCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($app_email_database, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($app_email_database, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($app_email_database, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($app_email_database, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Remark:</th>
  <td><?php echo object_input_tag($app_email_database, 'getRemark', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($app_email_database->getEmailId()): ?>
  &nbsp;<?php echo link_to('delete', 'appEmailDatabase/delete?email_id='.$app_email_database->getEmailId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'appEmailDatabase/show?email_id='.$app_email_database->getEmailId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'appEmailDatabase/list') ?>
<?php endif; ?>
</form>
