<?php
// auto-generated by sfPropelCrud
// date: 2013/12/31 10:47:22
?>
<h1>appEmailDatabase</h1>

<table>
<thead>
<tr>
  <th>Email</th>
  <th>Email</th>
  <th>Status code</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
  <th>Remark</th>
</tr>
</thead>
<tbody>
<?php foreach ($app_email_databases as $app_email_database): ?>
<tr>
    <td><?php echo link_to($app_email_database->getEmailId(), 'appEmailDatabase/show?email_id='.$app_email_database->getEmailId()) ?></td>
      <td><?php echo $app_email_database->getEmail() ?></td>
      <td><?php echo $app_email_database->getStatusCode() ?></td>
      <td><?php echo $app_email_database->getCreatedBy() ?></td>
      <td><?php echo $app_email_database->getCreatedOn() ?></td>
      <td><?php echo $app_email_database->getUpdatedBy() ?></td>
      <td><?php echo $app_email_database->getUpdatedOn() ?></td>
      <td><?php echo $app_email_database->getRemark() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'appEmailDatabase/create') ?>
