<?php
// auto-generated by sfPropelCrud
// date: 2013/12/31 10:47:22
?>
<table>
<tbody>
<tr>
<th>Email: </th>
<td><?php echo $app_email_database->getEmailId() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $app_email_database->getEmail() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $app_email_database->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $app_email_database->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $app_email_database->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $app_email_database->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $app_email_database->getUpdatedOn() ?></td>
</tr>
<tr>
<th>Remark: </th>
<td><?php echo $app_email_database->getRemark() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'appEmailDatabase/edit?email_id='.$app_email_database->getEmailId()) ?>
&nbsp;<?php echo link_to('list', 'appEmailDatabase/list') ?>
