<?php
// auto-generated by sfPropelCrud
// date: 2013/06/18 11:00:47
?>
<table>
<tbody>
<tr>
<th>Ime: </th>
<td><?php echo $ime_registration->getImeId() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $ime_registration->getFullName() ?></td>
</tr>
<tr>
<th>Full name chinese: </th>
<td><?php echo $ime_registration->getFullNameChinese() ?></td>
</tr>
<tr>
<th>Distributor code: </th>
<td><?php echo $ime_registration->getDistributorCode() ?></td>
</tr>
<tr>
<th>Passport number: </th>
<td><?php echo $ime_registration->getPassportNumber() ?></td>
</tr>
<tr>
<th>Nationality: </th>
<td><?php echo $ime_registration->getNationality() ?></td>
</tr>
<tr>
<th>Mobile no: </th>
<td><?php echo $ime_registration->getMobileNo() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $ime_registration->getEmail() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $ime_registration->getDistId() ?></td>
</tr>
<tr>
<th>Account: </th>
<td><?php echo $ime_registration->getAccountId() ?></td>
</tr>
<tr>
<th>Account type: </th>
<td><?php echo $ime_registration->getAccountType() ?></td>
</tr>
<tr>
<th>Qty: </th>
<td><?php echo $ime_registration->getQty() ?></td>
</tr>
<tr>
<th>Sub total: </th>
<td><?php echo $ime_registration->getSubTotal() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $ime_registration->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $ime_registration->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $ime_registration->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $ime_registration->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $ime_registration->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'imeRegistration/edit?ime_id='.$ime_registration->getImeId()) ?>
&nbsp;<?php echo link_to('list', 'imeRegistration/list') ?>
