<?php
// auto-generated by sfPropelCrud
// date: 2013/08/10 00:16:00
?>
<?php use_helper('Object') ?>

<?php echo form_tag('abfxDistMt4/update') ?>

<?php echo object_input_hidden_tag($abfx_dist_mt4, 'getAbfxId') ?>

<table>
<tbody>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Dist code:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getDistCode', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Full name:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getFullName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Mt4 user name:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getMt4UserName', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Mt4 password:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getMt4Password', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>File name:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getFileName', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getStatusCode', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($abfx_dist_mt4, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($abfx_dist_mt4, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($abfx_dist_mt4, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($abfx_dist_mt4->getAbfxId()): ?>
  &nbsp;<?php echo link_to('delete', 'abfxDistMt4/delete?abfx_id='.$abfx_dist_mt4->getAbfxId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'abfxDistMt4/show?abfx_id='.$abfx_dist_mt4->getAbfxId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'abfxDistMt4/list') ?>
<?php endif; ?>
</form>
