<?php
// auto-generated by sfPropelCrud
// date: 2013/08/10 00:16:00
?>
<h1>abfxDistMt4</h1>

<table>
<thead>
<tr>
  <th>Abfx</th>
  <th>Dist</th>
  <th>Dist code</th>
  <th>Email</th>
  <th>Full name</th>
  <th>Mt4 user name</th>
  <th>Mt4 password</th>
  <th>File name</th>
  <th>Status code</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($abfx_dist_mt4s as $abfx_dist_mt4): ?>
<tr>
    <td><?php echo link_to($abfx_dist_mt4->getAbfxId(), 'abfxDistMt4/show?abfx_id='.$abfx_dist_mt4->getAbfxId()) ?></td>
      <td><?php echo $abfx_dist_mt4->getDistId() ?></td>
      <td><?php echo $abfx_dist_mt4->getDistCode() ?></td>
      <td><?php echo $abfx_dist_mt4->getEmail() ?></td>
      <td><?php echo $abfx_dist_mt4->getFullName() ?></td>
      <td><?php echo $abfx_dist_mt4->getMt4UserName() ?></td>
      <td><?php echo $abfx_dist_mt4->getMt4Password() ?></td>
      <td><?php echo $abfx_dist_mt4->getFileName() ?></td>
      <td><?php echo $abfx_dist_mt4->getStatusCode() ?></td>
      <td><?php echo $abfx_dist_mt4->getCreatedBy() ?></td>
      <td><?php echo $abfx_dist_mt4->getCreatedOn() ?></td>
      <td><?php echo $abfx_dist_mt4->getUpdatedBy() ?></td>
      <td><?php echo $abfx_dist_mt4->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'abfxDistMt4/create') ?>
