<?php
// auto-generated by sfPropelCrud
// date: 2012/06/17 13:09:24
?>
<?php

/**
 * zMlmPackage actions.
 *
 * @package    sf_sandbox
 * @subpackage zMlmPackage
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class zMlmPackageActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('zMlmPackage', 'list');
  }

  public function executeList()
  {
    $this->mlm_packages = MlmPackagePeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->mlm_package = MlmPackagePeer::retrieveByPk($this->getRequestParameter('package_id'));
    $this->forward404Unless($this->mlm_package);
  }

  public function executeCreate()
  {
    $this->mlm_package = new MlmPackage();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->mlm_package = MlmPackagePeer::retrieveByPk($this->getRequestParameter('package_id'));
    $this->forward404Unless($this->mlm_package);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('package_id'))
    {
      $mlm_package = new MlmPackage();
    }
    else
    {
      $mlm_package = MlmPackagePeer::retrieveByPk($this->getRequestParameter('package_id'));
      $this->forward404Unless($mlm_package);
    }

    $mlm_package->setPackageId($this->getRequestParameter('package_id'));
    $mlm_package->setPackageName($this->getRequestParameter('package_name'));
    $mlm_package->setPrice($this->getRequestParameter('price'));
    $mlm_package->setCommission($this->getRequestParameter('commission'));
    $mlm_package->setPips($this->getRequestParameter('pips'));
    $mlm_package->setGeneration($this->getRequestParameter('generation'));
    $mlm_package->setPips2($this->getRequestParameter('pips2'));
    $mlm_package->setGeneration2($this->getRequestParameter('generation2'));
    $mlm_package->setCreatedBy($this->getRequestParameter('created_by'));
    if ($this->getRequestParameter('created_on'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('created_on'), $this->getUser()->getCulture());
      $mlm_package->setCreatedOn("$y-$m-$d");
    }
    $mlm_package->setUpdatedBy($this->getRequestParameter('updated_by'));
    if ($this->getRequestParameter('updated_on'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('updated_on'), $this->getUser()->getCulture());
      $mlm_package->setUpdatedOn("$y-$m-$d");
    }

    $mlm_package->save();

    return $this->redirect('zMlmPackage/show?package_id='.$mlm_package->getPackageId());
  }

  public function executeDelete()
  {
    $mlm_package = MlmPackagePeer::retrieveByPk($this->getRequestParameter('package_id'));

    $this->forward404Unless($mlm_package);

    $mlm_package->delete();

    return $this->redirect('zMlmPackage/list');
  }
}
