<?php
// auto-generated by sfPropelCrud
// date: 2012/05/29 07:08:12
?>
<h1>zMlmDistBankslip</h1>

<table>
<thead>
<tr>
  <th>Bankslip</th>
  <th>Dist</th>
  <th>Rank</th>
  <th>Rank code</th>
  <th>Amount</th>
  <th>Transaction type</th>
  <th>Image src</th>
  <th>Status code</th>
  <th>Remarks</th>
  <th>Approve reject datetime</th>
  <th>Approved by userid</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_dist_bankslips as $mlm_dist_bankslip): ?>
<tr>
    <td><?php echo link_to($mlm_dist_bankslip->getBankslipId(), 'zMlmDistBankslip/show?bankslip_id='.$mlm_dist_bankslip->getBankslipId()) ?></td>
      <td><?php echo $mlm_dist_bankslip->getDistId() ?></td>
      <td><?php echo $mlm_dist_bankslip->getRankId() ?></td>
      <td><?php echo $mlm_dist_bankslip->getRankCode() ?></td>
      <td><?php echo $mlm_dist_bankslip->getAmount() ?></td>
      <td><?php echo $mlm_dist_bankslip->getTransactionType() ?></td>
      <td><?php echo $mlm_dist_bankslip->getImageSrc() ?></td>
      <td><?php echo $mlm_dist_bankslip->getStatusCode() ?></td>
      <td><?php echo $mlm_dist_bankslip->getRemarks() ?></td>
      <td><?php echo $mlm_dist_bankslip->getApproveRejectDatetime() ?></td>
      <td><?php echo $mlm_dist_bankslip->getApprovedByUserid() ?></td>
      <td><?php echo $mlm_dist_bankslip->getCreatedBy() ?></td>
      <td><?php echo $mlm_dist_bankslip->getCreatedOn() ?></td>
      <td><?php echo $mlm_dist_bankslip->getUpdatedBy() ?></td>
      <td><?php echo $mlm_dist_bankslip->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmDistBankslip/create') ?>
