<?php
// auto-generated by sfPropelCrud
// date: 2012/06/17 13:09:24
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmPackage/update') ?>

<?php echo object_input_hidden_tag($mlm_package, 'getPackageId') ?>

<table>
<tbody>
<tr>
  <th>Package name*:</th>
  <td><?php echo object_input_tag($mlm_package, 'getPackageName', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Price:</th>
  <td><?php echo object_input_tag($mlm_package, 'getPrice', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Commission:</th>
  <td><?php echo object_input_tag($mlm_package, 'getCommission', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Pips:</th>
  <td><?php echo object_input_tag($mlm_package, 'getPips', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Generation:</th>
  <td><?php echo object_input_tag($mlm_package, 'getGeneration', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Pips2:</th>
  <td><?php echo object_input_tag($mlm_package, 'getPips2', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Generation2:</th>
  <td><?php echo object_input_tag($mlm_package, 'getGeneration2', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_package, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_package, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_package, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_package, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_package->getPackageId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmPackage/delete?package_id='.$mlm_package->getPackageId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmPackage/show?package_id='.$mlm_package->getPackageId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmPackage/list') ?>
<?php endif; ?>
</form>
