<?php
// auto-generated by sfPropelCrud
// date: 2012/05/17 13:43:36
?>
<h1>zMlmMd4Account</h1>

<table>
<thead>
<tr>
  <th>Md4</th>
  <th>Distributor</th>
  <th>Package</th>
  <th>Md user name</th>
  <th>Investor password</th>
  <th>Normal password</th>
  <th>Serial no</th>
  <th>Status code</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_md4_accounts as $mlm_md4_account): ?>
<tr>
    <td><?php echo link_to($mlm_md4_account->getMd4Id(), 'zMlmMd4Account/show?md4_id='.$mlm_md4_account->getMd4Id()) ?></td>
      <td><?php echo $mlm_md4_account->getDistributorId() ?></td>
      <td><?php echo $mlm_md4_account->getPackageId() ?></td>
      <td><?php echo $mlm_md4_account->getMdUserName() ?></td>
      <td><?php echo $mlm_md4_account->getInvestorPassword() ?></td>
      <td><?php echo $mlm_md4_account->getNormalPassword() ?></td>
      <td><?php echo $mlm_md4_account->getSerialNo() ?></td>
      <td><?php echo $mlm_md4_account->getStatusCode() ?></td>
      <td><?php echo $mlm_md4_account->getCreatedBy() ?></td>
      <td><?php echo $mlm_md4_account->getCreatedOn() ?></td>
      <td><?php echo $mlm_md4_account->getUpdatedBy() ?></td>
      <td><?php echo $mlm_md4_account->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmMd4Account/create') ?>
