<?php
// auto-generated by sfPropelCrud
// date: 2012/05/17 13:43:36
?>
<table>
<tbody>
<tr>
<th>Md4: </th>
<td><?php echo $mlm_md4_account->getMd4Id() ?></td>
</tr>
<tr>
<th>Distributor: </th>
<td><?php echo $mlm_md4_account->getDistributorId() ?></td>
</tr>
<tr>
<th>Package: </th>
<td><?php echo $mlm_md4_account->getPackageId() ?></td>
</tr>
<tr>
<th>Md user name: </th>
<td><?php echo $mlm_md4_account->getMdUserName() ?></td>
</tr>
<tr>
<th>Investor password: </th>
<td><?php echo $mlm_md4_account->getInvestorPassword() ?></td>
</tr>
<tr>
<th>Normal password: </th>
<td><?php echo $mlm_md4_account->getNormalPassword() ?></td>
</tr>
<tr>
<th>Serial no: </th>
<td><?php echo $mlm_md4_account->getSerialNo() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_md4_account->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_md4_account->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_md4_account->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_md4_account->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_md4_account->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmMd4Account/edit?md4_id='.$mlm_md4_account->getMd4Id()) ?>
&nbsp;<?php echo link_to('list', 'zMlmMd4Account/list') ?>
