advanceEpoint:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_ADVANCE_EPOINT ]]

advanceEcash:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_ADVANCE_ECASH ]]

cp3Withdrawal:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_CP3_WITHDRAWAL ]]

cp3Transfer:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_DIST_LIST ]]

dailyBonus:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_DAILY_BONUS ]]

dailySales:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_DAILY_SALES ]]

debitRollingPoint:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_DEBIT_ROLLING_POINT ]]

ecashWithdrawal:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_ECASH_WITHDRAWAL ]]

ecashTransaction:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_ECASH_TRANSACTION ]]

epointTransaction:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_EPOINT_TRANSACTION ]]

epointTransfer:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_EPOINT_TRANSFER ]]

epointPurchase:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_EPOINT_PURCHASE ]]

epointPurchaseEdit:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_EPOINT_PURCHASE ]]

monthlyBonus:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MONTHLY_BONUS ]]

monthlySales:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MONTHLY_SALES ]]

mt4WithdrawalEdit:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MT4_WITHDRAWAL ]]

mt4Withdrawal:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MT4_WITHDRAWAL ]]

packagePurchase:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE_PURCHASE ]]

packageUpgradeHistory:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE_UPGRADE ]]

packageUpgradeHistoryEdit:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE_UPGRADE ]]

pipsBonusDetail:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PIPS_BONUS ]]

referralBonusEdit:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_REFERRAL_BONUS ]]

referralBonus:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_REFERRAL_BONUS ]]

reloadMt4FundEdit:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_RELOAD_MT4_FUND ]]

reloadMt4Fund:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_RELOAD_MT4_FUND ]]

rollingPointList:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_REPORT_ROLLING_POINT ]]

transferRollingPoint:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_CREDIT_ROLLING_POINT ]]

updateReferralBonus:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_REFERRAL_BONUS ]]

updateReloadMt4Fund:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_RELOAD_MT4_FUND ]]

updateMt4Withdrawal:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MT4_WITHDRAWAL ]]

updatePurchaseEPoint:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_EPOINT_PURCHASE ]]

updatePackageUpgrade:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE_UPGRADE ]]

productPurchase:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MAX_STORE ]]

productPurchaseEdit:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MAX_STORE ]]

updateProductPurchase:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_MAX_STORE ]]

all:
  is_secure:  off        # off is the default value anyway