<?php
// auto-generated by sfPropelCrud
// date: 2013/11/25 17:45:37
?>
<h1>zLegalWatch</h1>

<table>
<thead>
<tr>
  <th>Watch</th>
  <th>Dist</th>
  <th>Full name</th>
  <th>Dist code</th>
  <th>Age</th>
  <th>Educationlevel</th>
  <th>Email</th>
  <th>Contact</th>
  <th>Message</th>
  <th>File name</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($legal_watchs as $legal_watch): ?>
<tr>
    <td><?php echo link_to($legal_watch->getWatchId(), 'zLegalWatch/show?watch_id='.$legal_watch->getWatchId()) ?></td>
      <td><?php echo $legal_watch->getDistId() ?></td>
      <td><?php echo $legal_watch->getFullName() ?></td>
      <td><?php echo $legal_watch->getDistCode() ?></td>
      <td><?php echo $legal_watch->getAge() ?></td>
      <td><?php echo $legal_watch->getEducationlevel() ?></td>
      <td><?php echo $legal_watch->getEmail() ?></td>
      <td><?php echo $legal_watch->getContact() ?></td>
      <td><?php echo $legal_watch->getMessage() ?></td>
      <td><?php echo $legal_watch->getFileName() ?></td>
      <td><?php echo $legal_watch->getCreatedBy() ?></td>
      <td><?php echo $legal_watch->getCreatedOn() ?></td>
      <td><?php echo $legal_watch->getUpdatedBy() ?></td>
      <td><?php echo $legal_watch->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zLegalWatch/create') ?>
