<?php
// auto-generated by sfPropelCrud
// date: 2013/11/25 17:45:37
?>
<table>
<tbody>
<tr>
<th>Watch: </th>
<td><?php echo $legal_watch->getWatchId() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $legal_watch->getDistId() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $legal_watch->getFullName() ?></td>
</tr>
<tr>
<th>Dist code: </th>
<td><?php echo $legal_watch->getDistCode() ?></td>
</tr>
<tr>
<th>Age: </th>
<td><?php echo $legal_watch->getAge() ?></td>
</tr>
<tr>
<th>Educationlevel: </th>
<td><?php echo $legal_watch->getEducationlevel() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $legal_watch->getEmail() ?></td>
</tr>
<tr>
<th>Contact: </th>
<td><?php echo $legal_watch->getContact() ?></td>
</tr>
<tr>
<th>Message: </th>
<td><?php echo $legal_watch->getMessage() ?></td>
</tr>
<tr>
<th>File name: </th>
<td><?php echo $legal_watch->getFileName() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $legal_watch->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $legal_watch->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $legal_watch->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $legal_watch->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zLegalWatch/edit?watch_id='.$legal_watch->getWatchId()) ?>
&nbsp;<?php echo link_to('list', 'zLegalWatch/list') ?>
