<?php
// auto-generated by sfPropelCrud
// date: 2012/04/20 19:13:40
?>
<?php use_helper('Object') ?>
<?php use_helper('I18N') ?>
<!-- TinyMCE -->
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
$(function() {
    $("#btnSave").button({
        icons: {
            primary: "ui-icon-circle-check"
        }
    });
});
</script>

<script type="text/javascript" language="javascript">
$(function() {
    $("#status option[value='<?php echo $status ?>']").prop("selected", true);

    $("#dataForm").validate({
        rules : {
            "startDate" : {
                required : true
            },
            "endDate" : {
                required : true
            }
        },
        submitHandler: function(form) {
            waiting();
            form.submit();
        }
    });

    $("#btnDelete").click(function() {
        if (confirm("Are you sure you wan to delete this record?")) {
            $("#act").val("doDelete");
            $("#dataForm").submit();
        }
    });

    $("#startDate").datepicker()
        .datepicker("setDate", "+0d")
        .change(function () {
            validateDate();
        });

    $("#endDate").datepicker()
        .datepicker("setDate", "+1y")
        .change(function() {
            validateDate();
        });

    function validateDate() {
        var sDate = new Date($("#startDate").val());
        var eDate = new Date($("#endDate").val());
        var msg = "";

        if (eDate <= sDate) {
            msg = "Warning: start date is earlier than or same with end date.";
        }

        $("#endDateWarning").html(msg);
    }
});

tinyMCE.init({
    // General options
    mode: "exact",
    elements: "title",
    theme: "simple",
    width: "100%",
    force_br_newlines: true,
    force_p_newlines: false
});

tinyMCE.init({
    // General options
    mode: "exact",
    elements: "content",
    theme: "simple",
    width: "100%",
    force_br_newlines: true,
    force_p_newlines: false
});
</script>

<style type="text/css">
    #endDateWarning {
        font-weight: bold;
        color: red;
    }
</style>

<?php echo form_tag('marketing/announcementDetail', array("id" => "dataForm")) ?>

<input type="hidden" name="announcementId" value="<?php echo $announcementId; ?>">
<input type="hidden" id="act" name="act" value="doSave">

<div style="padding: 10px; top: 10px; width: 98%">
    <div class="portlet">
        <div class="portlet-header">Announcement Details</div>
        <div class="portlet-content" style="width: 98%">
            <table class="sf_admin_list" cellpadding="3" width="100%">
                <tr>
                    <td colspan="2">
                        <?php if ($sf_flash->has('successMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-highlight ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-info"></span>
                                    <strong><?php echo $sf_flash->get('successMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if ($sf_flash->has('errorMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-error ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                                    <strong><?php echo $sf_flash->get('errorMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="caption">Title</td>
                    <td class="value">
                        <textarea rows="3" cols="3" id="title" name="title"><?php echo $title; ?></textarea>
                    </td>
                </tr>
                <tr class="tbl_form_row_even">
                    <td>
                        <?php echo __('Content') ?>
                    </td>
                    <td>
                        <textarea rows="3" cols="3" id="content" name="content"><?php echo $content; ?></textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo __('Status') ?>
                    </td>
                    <td>
                        <select id="status" name="status">
                            <option value="<?php echo Globals::STATUS_ACTIVE ?>">ACTIVE</option>
                            <option value="<?php echo Globals::STATUS_CLOSED ?>">CLOSED</option>
                        </select>
                    </td>
                </tr>
                <tr class="tbl_form_row_even">
                    <td>
                        <?php echo __('Start Date') ?>
                    </td>
                    <td>
                        <input type="text" id="startDate" name="startDate" value="<?php echo $startDate ?>" />
                    </td>
                </tr>
                <tr class="tbl_form_row_even">
                    <td>
                        <?php echo __('End Date') ?>
                    </td>
                    <td>
                        <input type="text" id="endDate" name="endDate" value="<?php echo $endDate ?>" />
                        <span id="endDateWarning"></span>
                    </td>
                </tr>
            </table>
            <hr/>
            <button id="btnSave" type="submit">Save</button>
            <button id="btnDelete" type="button">Delete</button>
        </div>
    </div>
</div>
</form>