<?php
// auto-generated by sfPropelCrud
// date: 2012/04/20 19:13:40
?>
<?php use_helper('Object') ?>
<?php use_helper('I18N') ?>
<!-- TinyMCE -->
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
$(function() {
    $("#btnSave").button({
            icons: {
                primary: "ui-icon-circle-check"
            }
        })
});
</script>

<style>
.ui-autocomplete-loading { background: white url('/images/loading2.gif') right center no-repeat; }
#distCode { width: 25em; }
</style>

<script type="text/javascript" language="javascript">
$(function() {
    $("#csForm").validate({
        messages : {
            transactionPassword: {
                remote: "Security Password is not valid."
            }
        },
        rules : {

        },
        submitHandler: function(form) {
            waiting();
            form.submit();
        }
    });

    $( "#distCode" ).autocomplete({
        source: function( request, response ) {
            $.ajax({
                type : 'POST',
                url : "<?php echo url_for('marketing/doRetrieveMemberData') ?>",
                dataType : 'json',
                cache: false,
                data: {
                    distCode : $('#distCode').val()
                },
                success: function( data ) {
                    response($.map(data.aaData, function( item ) {
                        return {
                            label: item[1],
                            value: item[0]
                        }
                    }));
                }
            });
        },
        minLength: 2,
        select: function( event, ui ) {

            /*log( ui.item ?
                "Selected: " + ui.item.label :
                "Nothing selected, input was " + this.value);*/
        },
        open: function() {
            $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
        },
        close: function() {
            $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
        }
    });
});

tinyMCE.init({
    // General options
    mode : "exact",
    elements : "message",
    theme : "simple",
    width: "100%"
});
</script>

<?php echo form_tag('marketing/doCustomerEnquiryDetail') ?>
<div style="padding: 10px; top: 10px; width: 98%">
    <div class="portlet">
        <div class="portlet-header">Customer Enquiry - New Message</div>
        <div class="portlet-content" style="width: 98%">

            <table class="sf_admin_list" cellpadding="3" width="100%">
                <tr>
                    <td colspan="2">
                        <?php if ($sf_flash->has('successMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-highlight ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-info"></span>
                                    <strong><?php echo $sf_flash->get('successMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if ($sf_flash->has('errorMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-error ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                                    <strong><?php echo $sf_flash->get('errorMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="caption">Title</td>
                    <td class="value">
                        <input type="text" name="title" id="title" value="<?php echo $title; ?>" size="50">
                    </td>
                </tr>
                <tr>
                    <td class="caption">Member ID</td>
                    <td class="value">
                        <input type="text" name="distId" id="distId" value="<?php echo $distId; ?>" size="50">
                        <input type="text" name="distCode" id="distCode" value="<?php echo $distCode; ?>" size="50">
                        <!--<select id="optMember" name="distId">
                            <?php
/*                                foreach ($dists as $dist) {
                            */?>
                                <option value="<?php /*echo $dist->getDistributorId();*/?>"><?php /*echo $dist->getDistributorCode()."-".$dist->getFullname();*/?></option>
                            <?php /*} */?>
                        </select>-->
                    </td>
                </tr>
                <tr class="tbl_form_row_even">
                    <td>
                        <?php echo __('Message') ?>
                    </td>
                    <td>
                        <textarea rows="3" cols="3" id="message" name="message"><?php echo $message; ?></textarea>
                    </td>
                </tr>
            </table>
            <hr/>
            <button id="btnSave">Save</button>
        </div>
    </div>
</div>
</form>