<?php
// auto-generated by sfPropelCrud
// date: 2012/05/29 07:08:12
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmDistBankslip/update') ?>

<?php echo object_input_hidden_tag($mlm_dist_bankslip, 'getBankslipId') ?>

<table>
<tbody>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Rank:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getRankId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Rank code:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getRankCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Amount*:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getAmount', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Transaction type*:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getTransactionType', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Image src:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getImageSrc', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getStatusCode', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Remarks:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getRemarks', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Approve reject datetime:</th>
  <td><?php echo object_input_date_tag($mlm_dist_bankslip, 'getApproveRejectDatetime', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Approved by userid:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getApprovedByUserid', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_dist_bankslip, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_dist_bankslip, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_dist_bankslip, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_dist_bankslip->getBankslipId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmDistBankslip/delete?bankslip_id='.$mlm_dist_bankslip->getBankslipId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmDistBankslip/show?bankslip_id='.$mlm_dist_bankslip->getBankslipId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmDistBankslip/list') ?>
<?php endif; ?>
</form>
