<?php
// auto-generated by sfPropelCrud
// date: 2012/05/29 07:08:12
?>
<table>
<tbody>
<tr>
<th>Bankslip: </th>
<td><?php echo $mlm_dist_bankslip->getBankslipId() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $mlm_dist_bankslip->getDistId() ?></td>
</tr>
<tr>
<th>Rank: </th>
<td><?php echo $mlm_dist_bankslip->getRankId() ?></td>
</tr>
<tr>
<th>Rank code: </th>
<td><?php echo $mlm_dist_bankslip->getRankCode() ?></td>
</tr>
<tr>
<th>Amount: </th>
<td><?php echo $mlm_dist_bankslip->getAmount() ?></td>
</tr>
<tr>
<th>Transaction type: </th>
<td><?php echo $mlm_dist_bankslip->getTransactionType() ?></td>
</tr>
<tr>
<th>Image src: </th>
<td><?php echo $mlm_dist_bankslip->getImageSrc() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_dist_bankslip->getStatusCode() ?></td>
</tr>
<tr>
<th>Remarks: </th>
<td><?php echo $mlm_dist_bankslip->getRemarks() ?></td>
</tr>
<tr>
<th>Approve reject datetime: </th>
<td><?php echo $mlm_dist_bankslip->getApproveRejectDatetime() ?></td>
</tr>
<tr>
<th>Approved by userid: </th>
<td><?php echo $mlm_dist_bankslip->getApprovedByUserid() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_dist_bankslip->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_dist_bankslip->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_dist_bankslip->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_dist_bankslip->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmDistBankslip/edit?bankslip_id='.$mlm_dist_bankslip->getBankslipId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmDistBankslip/list') ?>
