<?php
// auto-generated by sfPropelCrud
// date: 2012/04/20 19:13:40
?>
<?php use_helper('Object') ?>
<?php use_helper('I18N') ?>
<!-- TinyMCE -->
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
$(function() {
    $("#btnSave").button({
            icons: {
                primary: "ui-icon-circle-check"
            }
        })
});
</script>

<?php echo form_tag('admin/applicationSettingUpdate') ?>
<div style="padding: 10px; top: 10px; width: 98%">
    <div class="portlet">
        <div class="portlet-header">Application Settings</div>
        <div class="portlet-content" style="width: 98%">
            <table class="sf_admin_list" cellpadding="3" width="100%">
                <tr>
                    <td colspan="3">
                        <?php if ($sf_flash->has('successMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-highlight ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-info"></span>
                                    <strong><?php echo $sf_flash->get('successMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if ($sf_flash->has('errorMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-error ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                                    <strong><?php echo $sf_flash->get('errorMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php
                    foreach ($app_settings as $app_setting):
                        //if (Globals::GOOGLE_ANALYTIC == $app_setting->getParameter())
                        //    continue;
                ?>
                <tr>
<!--                    <td>--><?php //echo link_to($app_setting->getSettingId(), 'zAppSetting/show?setting_id=' . $app_setting->getSettingId()) ?><!--</td>-->
                    <td class="caption" style="width: 20%"><?php echo $app_setting->getSettingParameter() ?></td>
                    <td class="value" style="width: 45%"><?php //echo $app_setting->getValue() ?>
                        <input type="text" name="<?php echo $app_setting->getSettingParameter() ?>" value="<?php echo $app_setting->getSettingValue() ?>" size="50">
                    </td>
                    <td class="value" style="width: 35%"><?php echo $app_setting->getSettingRemark() ?></td>
                </tr>
                    <?php endforeach; ?>
            </table>
            <hr/>
            <button id="btnSave">Save</button>
        </div>
    </div>
</div>
</form>