<?php
// auto-generated by sfPropelCrud
// date: 2012/04/20 19:13:40
?>
<?php use_helper('Object') ?>
<?php use_helper('I18N') ?>

<script type="text/javascript">
    $(function() {
        $(".editLink").button({
            icons: {
                primary: "ui-icon-circle-check"
            }
        });
        $("#btnCreate").button({
            icons: {
                primary: "ui-icon-circle-plus"
            }
        })
    });
</script>

<?php echo form_tag('admin/packageUpdate') ?>

<?php echo object_input_hidden_tag($mlm_package, 'getPackageId') ?>

<div style="padding: 10px; top: 10px; width: 95%">
    <div class="portlet">
        <div class="portlet-header">Package</div>
        <div class="portlet-content">
            <table class="sf_admin_list" cellpadding="3" width="100%">
                <tr>
                    <td colspan="2">
                        <?php if ($sf_flash->has('successMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-highlight ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-info"></span>
                                    <strong><?php echo $sf_flash->get('successMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php if ($sf_flash->has('errorMsg')): ?>
                        <div class="ui-widget">
                            <div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-error ui-corner-all">
                                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                                    <strong><?php echo $sf_flash->get('errorMsg') ?></strong></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th class="caption">Package name*:</th>
                    <td class="value"><?php echo object_input_tag($mlm_package, 'getPackageName', array(
                                                                                                       'size' => 20,
                                                                                                  )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Price:</th>
                    <td class="value"><?php echo object_input_tag($mlm_package, 'getPrice', array(
                                                                                                 'size' => 7,
                                                                                            )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Commission:</th>
                    <td class="value"><?php echo object_input_tag($mlm_package, 'getCommission', array(
                                                                                                      'size' => 7,
                                                                                                 )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Pips:</th>
                    <td class="value"><?php echo object_input_tag($mlm_package, 'getCreditRefund', array(
                                                                                                'size' => 7,
                                                                                           )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Generation:</th>
                    <td class="value"><?php echo object_input_tag($mlm_package, 'getPairingBonus', array(
                                                                                                      'size' => 7,
                                                                                                 )) ?></td>
                </tr>
                <tr>
                    <th class="caption">Pips2:</th>
                    <td class="value"><?php echo object_input_tag($mlm_package, 'getDailyMaxPairing', array(
                                                                                                 'size' => 7,
                                                                                            )) ?></td>
                </tr>

                <tr>
                    <th class="caption">Display on client side:</th>
                    <td class="value"><?php
                        $arr = array();
                        $arr[Globals::YES] = 'Yes';
                        $arr[Globals::NO] = 'No';
                        echo select_tag('public_purchase', options_for_select($arr, $mlm_package->getPublicPurchase()));
                     ?></td>
                </tr>
                </tbody>
            </table>
            <hr/>
            <button id="btnSave">Save</button>
            &nbsp;<?php echo link_to('cancel', 'admin/packageList', array("id" => "btnCancel")) ?>
        </div>
    </div>
</div>
</form>
