<?php
// auto-generated by sfPropelCrud
// date: 2012/09/07 00:19:28
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmDistMt4/update') ?>

<?php echo object_input_hidden_tag($mlm_dist_mt4, 'getMt4Id') ?>

<table>
<tbody>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($mlm_dist_mt4, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Mt4 user name:</th>
  <td><?php echo object_input_tag($mlm_dist_mt4, 'getMt4UserName', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Mt4 password:</th>
  <td><?php echo object_input_tag($mlm_dist_mt4, 'getMt4Password', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_dist_mt4, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($mlm_dist_mt4, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_dist_mt4, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($mlm_dist_mt4, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_dist_mt4->getMt4Id()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmDistMt4/delete?mt4_id='.$mlm_dist_mt4->getMt4Id(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmDistMt4/show?mt4_id='.$mlm_dist_mt4->getMt4Id()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmDistMt4/list') ?>
<?php endif; ?>
</form>
