<?php
// auto-generated by sfPropelCrud
// date: 2012/09/07 00:19:28
?>
<table>
<tbody>
<tr>
<th>Mt4: </th>
<td><?php echo $mlm_dist_mt4->getMt4Id() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $mlm_dist_mt4->getDistId() ?></td>
</tr>
<tr>
<th>Mt4 user name: </th>
<td><?php echo $mlm_dist_mt4->getMt4UserName() ?></td>
</tr>
<tr>
<th>Mt4 password: </th>
<td><?php echo $mlm_dist_mt4->getMt4Password() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_dist_mt4->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_dist_mt4->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_dist_mt4->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_dist_mt4->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmDistMt4/edit?mt4_id='.$mlm_dist_mt4->getMt4Id()) ?>
&nbsp;<?php echo link_to('list', 'zMlmDistMt4/list') ?>
