<?php
// auto-generated by sfPropelCrud
// date: 2012/11/21 21:11:05
?>
<h1>zMlmMemberQuestionnaire</h1>

<table>
<thead>
<tr>
  <th>Questionnaire</th>
  <th>Member</th>
  <th>Q1</th>
  <th>Q2</th>
  <th>Q3</th>
  <th>Q4</th>
  <th>Q5</th>
  <th>Q6</th>
  <th>Q7</th>
  <th>Q8</th>
  <th>S1</th>
  <th>S2</th>
  <th>S3</th>
  <th>Status code</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_member_questionnaires as $mlm_member_questionnaire): ?>
<tr>
    <td><?php echo link_to($mlm_member_questionnaire->getQuestionnaireId(), 'zMlmMemberQuestionnaire/show?questionnaire_id='.$mlm_member_questionnaire->getQuestionnaireId()) ?></td>
      <td><?php echo $mlm_member_questionnaire->getMemberId() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ1() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ2() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ3() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ4() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ5() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ6() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ7() ?></td>
      <td><?php echo $mlm_member_questionnaire->getQ8() ?></td>
      <td><?php echo $mlm_member_questionnaire->getS1() ?></td>
      <td><?php echo $mlm_member_questionnaire->getS2() ?></td>
      <td><?php echo $mlm_member_questionnaire->getS3() ?></td>
      <td><?php echo $mlm_member_questionnaire->getStatusCode() ?></td>
      <td><?php echo $mlm_member_questionnaire->getCreatedBy() ?></td>
      <td><?php echo $mlm_member_questionnaire->getCreatedOn() ?></td>
      <td><?php echo $mlm_member_questionnaire->getUpdatedBy() ?></td>
      <td><?php echo $mlm_member_questionnaire->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmMemberQuestionnaire/create') ?>
