bdetailsSuccess:
  has_layout:     off
  stylesheets: 	  []

papSuccessDatafeedSuccess:
  has_layout:     off
  stylesheets: 	  []

certificateSuccess:
  has_layout:     off
  stylesheets: 	  []

demoAccountSuccess:
  has_layout:     off
  stylesheets: 	  []

liveAccountSuccess:
  has_layout:     off
  stylesheets: 	  []

forgetPasswordSuccess:
  has_layout:     off
  stylesheets: 	  []

printBankInformationSuccess:
  has_layout:     off
  stylesheets: 	  []

registerSuccess:
  has_layout:     off
  stylesheets: 	  []

registerInfoSuccess:
  has_layout:     off
  stylesheets: 	  []

epointPurchasePGSuccess:
  has_layout:     off
  stylesheets: 	  []

epointPurchaseGozSuccess:
  has_layout:     off
  stylesheets: 	  []

epointPurchasePaPSuccess:
  has_layout:     off
  stylesheets: 	  []

paymentGatewaySuccess:
  has_layout:     off
  stylesheets: 	  []

paymentGatewayGozSuccess:
  has_layout:     off
  stylesheets: 	  []