adminUserList:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_USER_LIST ]]

roleList:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_USER_ROLE ]]

distList:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_DIST_LIST ]]

all:
  is_secure:  off        # off is the default value anyway