<?php
// auto-generated by sfPropelCrud
// date: 2013/11/25 17:45:37
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zLegalWatch/update') ?>

<?php echo object_input_hidden_tag($legal_watch, 'getWatchId') ?>

<table>
<tbody>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($legal_watch, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Full name:</th>
  <td><?php echo object_input_tag($legal_watch, 'getFullName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dist code:</th>
  <td><?php echo object_input_tag($legal_watch, 'getDistCode', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Age:</th>
  <td><?php echo object_input_tag($legal_watch, 'getAge', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Educationlevel:</th>
  <td><?php echo object_input_tag($legal_watch, 'getEducationlevel', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($legal_watch, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Contact:</th>
  <td><?php echo object_input_tag($legal_watch, 'getContact', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Message:</th>
  <td><?php echo object_textarea_tag($legal_watch, 'getMessage', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>File name:</th>
  <td><?php echo object_input_tag($legal_watch, 'getFileName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($legal_watch, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($legal_watch, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($legal_watch, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($legal_watch, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($legal_watch->getWatchId()): ?>
  &nbsp;<?php echo link_to('delete', 'zLegalWatch/delete?watch_id='.$legal_watch->getWatchId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zLegalWatch/show?watch_id='.$legal_watch->getWatchId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zLegalWatch/list') ?>
<?php endif; ?>
</form>
