<?php
// auto-generated by sfPropelCrud
// date: 2013/07/13 09:24:04
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zImeReport/update') ?>

<?php echo object_input_hidden_tag($ime_report, 'getReportId') ?>

<table>
<tbody>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($ime_report, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Bonus type*:</th>
  <td><?php echo object_input_tag($ime_report, 'getBonusType', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Small leg*:</th>
  <td><?php echo object_input_tag($ime_report, 'getSmallLeg', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Personal sales*:</th>
  <td><?php echo object_input_tag($ime_report, 'getPersonalSales', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Ticket qty:</th>
  <td><?php echo object_input_tag($ime_report, 'getTicketQty', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Distributor code:</th>
  <td><?php echo object_input_tag($ime_report, 'getDistributorCode', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Full name:</th>
  <td><?php echo object_input_tag($ime_report, 'getFullName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($ime_report, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Contact:</th>
  <td><?php echo object_input_tag($ime_report, 'getContact', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Country:</th>
  <td><?php echo object_input_tag($ime_report, 'getCountry', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Registered on*:</th>
  <td><?php echo object_input_date_tag($ime_report, 'getRegisteredOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Leader:</th>
  <td><?php echo object_input_tag($ime_report, 'getLeader', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Remark:</th>
  <td><?php echo object_input_tag($ime_report, 'getRemark', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($ime_report, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($ime_report, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($ime_report, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($ime_report, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($ime_report->getReportId()): ?>
  &nbsp;<?php echo link_to('delete', 'zImeReport/delete?report_id='.$ime_report->getReportId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zImeReport/show?report_id='.$ime_report->getReportId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zImeReport/list') ?>
<?php endif; ?>
</form>
