pinTransactionLogList:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

placementLogList:
  is_secure:   on
  credentials: [[ OFX_MY_DISTRIBUTOR ]]

all:
  is_secure:  off        # off is the default value anyway