default:
  http_metas:
    content-type: text/html

  metas:
    title:        Maxim Trader
    robots:       Maxim Trader
    description:  Maxim Trader
    keywords:     Maxim Trader
    language:     cn

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
