<?php
// auto-generated by sfPropelCrud
// date: 2012/06/17 13:09:24
?>
<h1>zMlmPackage</h1>

<table>
<thead>
<tr>
  <th>Package</th>
  <th>Package name</th>
  <th>Price</th>
  <th>Commission</th>
  <th>Pips</th>
  <th>Generation</th>
  <th>Pips2</th>
  <th>Generation2</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_packages as $mlm_package): ?>
<tr>
    <td><?php echo link_to($mlm_package->getPackageId(), 'zMlmPackage/show?package_id='.$mlm_package->getPackageId()) ?></td>
      <td><?php echo $mlm_package->getPackageName() ?></td>
      <td><?php echo $mlm_package->getPrice() ?></td>
      <td><?php echo $mlm_package->getCommission() ?></td>
      <td><?php echo $mlm_package->getPips() ?></td>
      <td><?php echo $mlm_package->getGeneration() ?></td>
      <td><?php echo $mlm_package->getPips2() ?></td>
      <td><?php echo $mlm_package->getGeneration2() ?></td>
      <td><?php echo $mlm_package->getCreatedBy() ?></td>
      <td><?php echo $mlm_package->getCreatedOn() ?></td>
      <td><?php echo $mlm_package->getUpdatedBy() ?></td>
      <td><?php echo $mlm_package->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmPackage/create') ?>
