<?php
// auto-generated by sfPropelCrud
// date: 2012/06/17 13:09:24
?>
<table>
<tbody>
<tr>
<th>Package: </th>
<td><?php echo $mlm_package->getPackageId() ?></td>
</tr>
<tr>
<th>Package name: </th>
<td><?php echo $mlm_package->getPackageName() ?></td>
</tr>
<tr>
<th>Price: </th>
<td><?php echo $mlm_package->getPrice() ?></td>
</tr>
<tr>
<th>Commission: </th>
<td><?php echo $mlm_package->getCommission() ?></td>
</tr>
<tr>
<th>Pips: </th>
<td><?php echo $mlm_package->getPips() ?></td>
</tr>
<tr>
<th>Generation: </th>
<td><?php echo $mlm_package->getGeneration() ?></td>
</tr>
<tr>
<th>Pips2: </th>
<td><?php echo $mlm_package->getPips2() ?></td>
</tr>
<tr>
<th>Generation2: </th>
<td><?php echo $mlm_package->getGeneration2() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_package->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_package->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_package->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_package->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmPackage/edit?package_id='.$mlm_package->getPackageId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmPackage/list') ?>
