<?php
// auto-generated by sfPropelCrud
// date: 2013/06/18 11:00:47
?>
<?php use_helper('Object') ?>

<?php echo form_tag('imeRegistration/update') ?>

<?php echo object_input_hidden_tag($ime_registration, 'getImeId') ?>

<table>
<tbody>
<tr>
  <th>Full name:</th>
  <td><?php echo object_input_tag($ime_registration, 'getFullName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Full name chinese:</th>
  <td><?php echo object_input_tag($ime_registration, 'getFullNameChinese', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Distributor code:</th>
  <td><?php echo object_input_tag($ime_registration, 'getDistributorCode', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Passport number:</th>
  <td><?php echo object_input_tag($ime_registration, 'getPassportNumber', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Nationality:</th>
  <td><?php echo object_input_tag($ime_registration, 'getNationality', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Mobile no:</th>
  <td><?php echo object_input_tag($ime_registration, 'getMobileNo', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($ime_registration, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dist*:</th>
  <td><?php echo object_input_tag($ime_registration, 'getDistId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Account*:</th>
  <td><?php echo object_input_tag($ime_registration, 'getAccountId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Account type*:</th>
  <td><?php echo object_input_tag($ime_registration, 'getAccountType', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Qty:</th>
  <td><?php echo object_input_tag($ime_registration, 'getQty', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Sub total*:</th>
  <td><?php echo object_input_tag($ime_registration, 'getSubTotal', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Status code:</th>
  <td><?php echo object_input_tag($ime_registration, 'getStatusCode', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($ime_registration, 'getCreatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Created on*:</th>
  <td><?php echo object_input_date_tag($ime_registration, 'getCreatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($ime_registration, 'getUpdatedBy', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Updated on*:</th>
  <td><?php echo object_input_date_tag($ime_registration, 'getUpdatedOn', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($ime_registration->getImeId()): ?>
  &nbsp;<?php echo link_to('delete', 'imeRegistration/delete?ime_id='.$ime_registration->getImeId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'imeRegistration/show?ime_id='.$ime_registration->getImeId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'imeRegistration/list') ?>
<?php endif; ?>
</form>
