index:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

announcement:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

announcementList:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

company:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

investment:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

maximExecutor:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

marketNews:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

contactUs:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR ]]

updatePassword:
  is_secure:   on
  credentials: [[ MAXIM_DISTRIBUTOR_PW_EXPIRED ]]

all:
  is_secure:  off        # off is the default value anyway