activities_26062013Success:
  has_layout:     off
  stylesheets: 	  []

activitiesShanghaiFudanSuccess:
  has_layout:     off
  stylesheets: 	  []

activitiesBusinessPreviewSuccess:
  has_layout:     off
  stylesheets: 	  []

activitiesFinancialMarketOutlookSuccess:
  has_layout:     off
  stylesheets: 	  []

activitiesShanghaiInternationalDinnerGatheringSuccess:
  has_layout:     off
  stylesheets: 	  []

activitiesShanghaiInvestmentManagementSuccess:
  has_layout:     off
  stylesheets: 	  []

activitiesSuccess:
  has_layout:     off
  stylesheets: 	  []

announcementListSuccess:
  has_layout:     off
  stylesheets: 	  []

announcementSuccess:
  has_layout:     off
  stylesheets: 	  []

companySuccess:
  has_layout:     off
  stylesheets: 	  []

contactUsSuccess:
  has_layout:     off
  stylesheets: 	  []

forgetPasswordSuccess:
  has_layout:     off
  stylesheets: 	  []

indexSuccess:
  has_layout:     off
  stylesheets: 	  []

index2Success:
  has_layout:     off
  stylesheets: 	  []

investmentSuccess:
  has_layout:     off
  stylesheets: 	  []

loginSuccess:
  has_layout:     off
  stylesheets: 	  []

login2Success:
  has_layout:     off
  stylesheets: 	  []

maintenanceSuccess:
  has_layout:     off
  stylesheets: 	  []

marketNewsSuccess:
  has_layout:     off
  stylesheets: 	  []

maximExecutorSuccess:
  has_layout:     off
  stylesheets: 	  []

memberRegistrationSuccess:
  has_layout:     off
  stylesheets: 	  []

redirectToBackendSuccess:
  has_layout:     off
  stylesheets: 	  []

rssSuccess:
  has_layout:     off
  stylesheets: 	  []

registerSuccess:
  has_layout:     off
  stylesheets: 	  []

register2Success:
  has_layout:     off
  stylesheets: 	  []

questionnaireSuccess:
  has_layout:     off
  stylesheets: 	  []

updatePasswordSuccess:
  has_layout:     off
  stylesheets: 	  []

accountSuspendedSuccess:
  has_layout:     off
  stylesheets: 	  []
