ap:
  is_secure:   on
  credentials: [ MAXIM_SUPERADMIN ]

applicationSetting:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_SETTING ]]

changePassword:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_CHANGE_PASSWORD ]]

dashboard:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_dashboard ]]

packageList:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE ]]

packageCreate:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE ]]

packageEdit:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE ]]

packageUpdate:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_PACKAGE ]]

userList:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_USER_LIST ]]

userRole:
  is_secure:   on
  credentials: [[ MAXIM_SUPERADMIN, MAXIM_AL_USER_ROLE ]]

all:
  is_secure:  off        # off is the default value anyway