ap:
  is_secure:   on
  credentials: [ OFX_MY_SUPERADMIN ]

applicationSetting:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_SETTING ]]

changePassword:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_CHANGE_PASSWORD ]]

dashboard:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_dashboard ]]

packageList:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_PACKAGE ]]

packageCreate:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_PACKAGE ]]

packageEdit:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_PACKAGE ]]

packageUpdate:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_PACKAGE ]]

userList:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_USER_LIST ]]

userRole:
  is_secure:   on
  credentials: [[ OFX_MY_SUPERADMIN, OFX_MY_AL_USER_ROLE ]]

all:
  is_secure:  off        # off is the default value anyway