<?php
// auto-generated by sfPropelCrud
// date: 2012/05/19 22:37:17
?>
<h1>zMlmReloadTopupHistory</h1>

<table>
<thead>
<tr>
  <th>Reload</th>
  <th>Dist</th>
  <th>Transaction code</th>
  <th>Balance</th>
  <th>Status code</th>
  <th>Remarks</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_reload_topup_historys as $mlm_reload_topup_history): ?>
<tr>
    <td><?php echo link_to($mlm_reload_topup_history->getReloadId(), 'zMlmReloadTopupHistory/show?reload_id='.$mlm_reload_topup_history->getReloadId()) ?></td>
      <td><?php echo $mlm_reload_topup_history->getDistId() ?></td>
      <td><?php echo $mlm_reload_topup_history->getTransactionCode() ?></td>
      <td><?php echo $mlm_reload_topup_history->getBalance() ?></td>
      <td><?php echo $mlm_reload_topup_history->getStatusCode() ?></td>
      <td><?php echo $mlm_reload_topup_history->getRemarks() ?></td>
      <td><?php echo $mlm_reload_topup_history->getCreatedBy() ?></td>
      <td><?php echo $mlm_reload_topup_history->getCreatedOn() ?></td>
      <td><?php echo $mlm_reload_topup_history->getUpdatedBy() ?></td>
      <td><?php echo $mlm_reload_topup_history->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmReloadTopupHistory/create') ?>
