<?php
// auto-generated by sfPropelCrud
// date: 2013/10/20 23:19:12
?>
<table>
<tbody>
<tr>
<th>Distributor: </th>
<td><?php echo $mlm_distributor->getDistributorId() ?></td>
</tr>
<tr>
<th>Distributor code: </th>
<td><?php echo $mlm_distributor->getDistributorCode() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $mlm_distributor->getUserId() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_distributor->getStatusCode() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $mlm_distributor->getFullName() ?></td>
</tr>
<tr>
<th>Nickname: </th>
<td><?php echo $mlm_distributor->getNickname() ?></td>
</tr>
<tr>
<th>Ic: </th>
<td><?php echo $mlm_distributor->getIc() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $mlm_distributor->getCountry() ?></td>
</tr>
<tr>
<th>Address: </th>
<td><?php echo $mlm_distributor->getAddress() ?></td>
</tr>
<tr>
<th>Address2: </th>
<td><?php echo $mlm_distributor->getAddress2() ?></td>
</tr>
<tr>
<th>City: </th>
<td><?php echo $mlm_distributor->getCity() ?></td>
</tr>
<tr>
<th>State: </th>
<td><?php echo $mlm_distributor->getState() ?></td>
</tr>
<tr>
<th>Postcode: </th>
<td><?php echo $mlm_distributor->getPostcode() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $mlm_distributor->getEmail() ?></td>
</tr>
<tr>
<th>Alternate email: </th>
<td><?php echo $mlm_distributor->getAlternateEmail() ?></td>
</tr>
<tr>
<th>Contact: </th>
<td><?php echo $mlm_distributor->getContact() ?></td>
</tr>
<tr>
<th>Gender: </th>
<td><?php echo $mlm_distributor->getGender() ?></td>
</tr>
<tr>
<th>Dob: </th>
<td><?php echo $mlm_distributor->getDob() ?></td>
</tr>
<tr>
<th>Bank name: </th>
<td><?php echo $mlm_distributor->getBankName() ?></td>
</tr>
<tr>
<th>Bank branch name: </th>
<td><?php echo $mlm_distributor->getBankBranchName() ?></td>
</tr>
<tr>
<th>Bank address: </th>
<td><?php echo $mlm_distributor->getBankAddress() ?></td>
</tr>
<tr>
<th>Bank acc no: </th>
<td><?php echo $mlm_distributor->getBankAccNo() ?></td>
</tr>
<tr>
<th>Bank holder name: </th>
<td><?php echo $mlm_distributor->getBankHolderName() ?></td>
</tr>
<tr>
<th>Bank swift code: </th>
<td><?php echo $mlm_distributor->getBankSwiftCode() ?></td>
</tr>
<tr>
<th>Visa debit card: </th>
<td><?php echo $mlm_distributor->getVisaDebitCard() ?></td>
</tr>
<tr>
<th>Ezy cash card: </th>
<td><?php echo $mlm_distributor->getEzyCashCard() ?></td>
</tr>
<tr>
<th>Tree level: </th>
<td><?php echo $mlm_distributor->getTreeLevel() ?></td>
</tr>
<tr>
<th>Tree structure: </th>
<td><?php echo $mlm_distributor->getTreeStructure() ?></td>
</tr>
<tr>
<th>Placement tree level: </th>
<td><?php echo $mlm_distributor->getPlacementTreeLevel() ?></td>
</tr>
<tr>
<th>Placement tree structure: </th>
<td><?php echo $mlm_distributor->getPlacementTreeStructure() ?></td>
</tr>
<tr>
<th>Init rank: </th>
<td><?php echo $mlm_distributor->getInitRankId() ?></td>
</tr>
<tr>
<th>Init rank code: </th>
<td><?php echo $mlm_distributor->getInitRankCode() ?></td>
</tr>
<tr>
<th>Upline dist: </th>
<td><?php echo $mlm_distributor->getUplineDistId() ?></td>
</tr>
<tr>
<th>Upline dist code: </th>
<td><?php echo $mlm_distributor->getUplineDistCode() ?></td>
</tr>
<tr>
<th>Tree upline dist: </th>
<td><?php echo $mlm_distributor->getTreeUplineDistId() ?></td>
</tr>
<tr>
<th>Tree upline dist code: </th>
<td><?php echo $mlm_distributor->getTreeUplineDistCode() ?></td>
</tr>
<tr>
<th>Total left: </th>
<td><?php echo $mlm_distributor->getTotalLeft() ?></td>
</tr>
<tr>
<th>Total right: </th>
<td><?php echo $mlm_distributor->getTotalRight() ?></td>
</tr>
<tr>
<th>Placement position: </th>
<td><?php echo $mlm_distributor->getPlacementPosition() ?></td>
</tr>
<tr>
<th>Placement datetime: </th>
<td><?php echo $mlm_distributor->getPlacementDatetime() ?></td>
</tr>
<tr>
<th>Rank: </th>
<td><?php echo $mlm_distributor->getRankId() ?></td>
</tr>
<tr>
<th>Rank code: </th>
<td><?php echo $mlm_distributor->getRankCode() ?></td>
</tr>
<tr>
<th>Active datetime: </th>
<td><?php echo $mlm_distributor->getActiveDatetime() ?></td>
</tr>
<tr>
<th>Activated by: </th>
<td><?php echo $mlm_distributor->getActivatedBy() ?></td>
</tr>
<tr>
<th>Leverage: </th>
<td><?php echo $mlm_distributor->getLeverage() ?></td>
</tr>
<tr>
<th>Spread: </th>
<td><?php echo $mlm_distributor->getSpread() ?></td>
</tr>
<tr>
<th>Deposit currency: </th>
<td><?php echo $mlm_distributor->getDepositCurrency() ?></td>
</tr>
<tr>
<th>Deposit amount: </th>
<td><?php echo $mlm_distributor->getDepositAmount() ?></td>
</tr>
<tr>
<th>Sign name: </th>
<td><?php echo $mlm_distributor->getSignName() ?></td>
</tr>
<tr>
<th>Sign date: </th>
<td><?php echo $mlm_distributor->getSignDate() ?></td>
</tr>
<tr>
<th>Term condition: </th>
<td><?php echo $mlm_distributor->getTermCondition() ?></td>
</tr>
<tr>
<th>Ib commission: </th>
<td><?php echo $mlm_distributor->getIbCommission() ?></td>
</tr>
<tr>
<th>Is ib: </th>
<td><?php echo $mlm_distributor->getIsIb() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_distributor->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_distributor->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_distributor->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_distributor->getUpdatedOn() ?></td>
</tr>
<tr>
<th>Package purchase flag: </th>
<td><?php echo $mlm_distributor->getPackagePurchaseFlag() ?></td>
</tr>
<tr>
<th>File bank pass book: </th>
<td><?php echo $mlm_distributor->getFileBankPassBook() ?></td>
</tr>
<tr>
<th>File proof of residence: </th>
<td><?php echo $mlm_distributor->getFileProofOfResidence() ?></td>
</tr>
<tr>
<th>File nric: </th>
<td><?php echo $mlm_distributor->getFileNric() ?></td>
</tr>
<tr>
<th>Excluded structure: </th>
<td><?php echo $mlm_distributor->getExcludedStructure() ?></td>
</tr>
<tr>
<th>Product mte: </th>
<td><?php echo $mlm_distributor->getProductMte() ?></td>
</tr>
<tr>
<th>Product fxgold: </th>
<td><?php echo $mlm_distributor->getProductFxgold() ?></td>
</tr>
<tr>
<th>Remark: </th>
<td><?php echo $mlm_distributor->getRemark() ?></td>
</tr>
<tr>
<th>Loan account: </th>
<td><?php echo $mlm_distributor->getLoanAccount() ?></td>
</tr>
<tr>
<th>Self register: </th>
<td><?php echo $mlm_distributor->getSelfRegister() ?></td>
</tr>
<tr>
<th>Debit account: </th>
<td><?php echo $mlm_distributor->getDebitAccount() ?></td>
</tr>
<tr>
<th>Debit rank: </th>
<td><?php echo $mlm_distributor->getDebitRankId() ?></td>
</tr>
<tr>
<th>Debit status code: </th>
<td><?php echo $mlm_distributor->getDebitStatusCode() ?></td>
</tr>
<tr>
<th>Hide genealogy: </th>
<td><?php echo $mlm_distributor->getHideGenealogy() ?></td>
</tr>
<tr>
<th>From abfx: </th>
<td><?php echo $mlm_distributor->getFromAbfx() ?></td>
</tr>
<tr>
<th>Abfx user: </th>
<td><?php echo $mlm_distributor->getAbfxUserId() ?></td>
</tr>
<tr>
<th>Abfx ref: </th>
<td><?php echo $mlm_distributor->getAbfxRef() ?></td>
</tr>
<tr>
<th>Abfx upline1: </th>
<td><?php echo $mlm_distributor->getAbfxUpline1() ?></td>
</tr>
<tr>
<th>Abfx position: </th>
<td><?php echo $mlm_distributor->getAbfxPosition() ?></td>
</tr>
<tr>
<th>Abfx remark: </th>
<td><?php echo $mlm_distributor->getAbfxRemark() ?></td>
</tr>
<tr>
<th>Abfx ewallet: </th>
<td><?php echo $mlm_distributor->getAbfxEwallet() ?></td>
</tr>
<tr>
<th>Abfx epoint: </th>
<td><?php echo $mlm_distributor->getAbfxEpoint() ?></td>
</tr>
<tr>
<th>Abfx pairing left: </th>
<td><?php echo $mlm_distributor->getAbfxPairingLeft() ?></td>
</tr>
<tr>
<th>Abfx pairing right: </th>
<td><?php echo $mlm_distributor->getAbfxPairingRight() ?></td>
</tr>
<tr>
<th>Migrated status: </th>
<td><?php echo $mlm_distributor->getMigratedStatus() ?></td>
</tr>
<tr>
<th>Migrated placement status: </th>
<td><?php echo $mlm_distributor->getMigratedPlacementStatus() ?></td>
</tr>
<tr>
<th>Migrate retry: </th>
<td><?php echo $mlm_distributor->getMigrateRetry() ?></td>
</tr>
<tr>
<th>Nominee name: </th>
<td><?php echo $mlm_distributor->getNomineeName() ?></td>
</tr>
<tr>
<th>Nominee ic: </th>
<td><?php echo $mlm_distributor->getNomineeIc() ?></td>
</tr>
<tr>
<th>Nominee relationship: </th>
<td><?php echo $mlm_distributor->getNomineeRelationship() ?></td>
</tr>
<tr>
<th>Nominee contactno: </th>
<td><?php echo $mlm_distributor->getNomineeContactno() ?></td>
</tr>
<tr>
<th>New activity flag: </th>
<td><?php echo $mlm_distributor->getNewActivityFlag() ?></td>
</tr>
<tr>
<th>New report flag: </th>
<td><?php echo $mlm_distributor->getNewReportFlag() ?></td>
</tr>
<tr>
<th>Q3 champions: </th>
<td><?php echo $mlm_distributor->getQ3Champions() ?></td>
</tr>
<tr>
<th>Q3 datetime: </th>
<td><?php echo $mlm_distributor->getQ3Datetime() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmDistributor/edit?distributor_id='.$mlm_distributor->getDistributorId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmDistributor/list') ?>
