<?php
// auto-generated by sfPropelCrud
// date: 2013/07/13 09:24:04
?>
<h1>zImeReport</h1>

<table>
<thead>
<tr>
  <th>Report</th>
  <th>Dist</th>
  <th>Bonus type</th>
  <th>Small leg</th>
  <th>Personal sales</th>
  <th>Ticket qty</th>
  <th>Distributor code</th>
  <th>Full name</th>
  <th>Email</th>
  <th>Contact</th>
  <th>Country</th>
  <th>Registered on</th>
  <th>Leader</th>
  <th>Remark</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($ime_reports as $ime_report): ?>
<tr>
    <td><?php echo link_to($ime_report->getReportId(), 'zImeReport/show?report_id='.$ime_report->getReportId()) ?></td>
      <td><?php echo $ime_report->getDistId() ?></td>
      <td><?php echo $ime_report->getBonusType() ?></td>
      <td><?php echo $ime_report->getSmallLeg() ?></td>
      <td><?php echo $ime_report->getPersonalSales() ?></td>
      <td><?php echo $ime_report->getTicketQty() ?></td>
      <td><?php echo $ime_report->getDistributorCode() ?></td>
      <td><?php echo $ime_report->getFullName() ?></td>
      <td><?php echo $ime_report->getEmail() ?></td>
      <td><?php echo $ime_report->getContact() ?></td>
      <td><?php echo $ime_report->getCountry() ?></td>
      <td><?php echo $ime_report->getRegisteredOn() ?></td>
      <td><?php echo $ime_report->getLeader() ?></td>
      <td><?php echo $ime_report->getRemark() ?></td>
      <td><?php echo $ime_report->getCreatedBy() ?></td>
      <td><?php echo $ime_report->getCreatedOn() ?></td>
      <td><?php echo $ime_report->getUpdatedBy() ?></td>
      <td><?php echo $ime_report->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zImeReport/create') ?>
