<?php
// auto-generated by sfPropelCrud
// date: 2013/07/13 09:24:04
?>
<table>
<tbody>
<tr>
<th>Report: </th>
<td><?php echo $ime_report->getReportId() ?></td>
</tr>
<tr>
<th>Dist: </th>
<td><?php echo $ime_report->getDistId() ?></td>
</tr>
<tr>
<th>Bonus type: </th>
<td><?php echo $ime_report->getBonusType() ?></td>
</tr>
<tr>
<th>Small leg: </th>
<td><?php echo $ime_report->getSmallLeg() ?></td>
</tr>
<tr>
<th>Personal sales: </th>
<td><?php echo $ime_report->getPersonalSales() ?></td>
</tr>
<tr>
<th>Ticket qty: </th>
<td><?php echo $ime_report->getTicketQty() ?></td>
</tr>
<tr>
<th>Distributor code: </th>
<td><?php echo $ime_report->getDistributorCode() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $ime_report->getFullName() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $ime_report->getEmail() ?></td>
</tr>
<tr>
<th>Contact: </th>
<td><?php echo $ime_report->getContact() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $ime_report->getCountry() ?></td>
</tr>
<tr>
<th>Registered on: </th>
<td><?php echo $ime_report->getRegisteredOn() ?></td>
</tr>
<tr>
<th>Leader: </th>
<td><?php echo $ime_report->getLeader() ?></td>
</tr>
<tr>
<th>Remark: </th>
<td><?php echo $ime_report->getRemark() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $ime_report->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $ime_report->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $ime_report->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $ime_report->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zImeReport/edit?report_id='.$ime_report->getReportId()) ?>
&nbsp;<?php echo link_to('list', 'zImeReport/list') ?>
